### ISSUE TITLE
Font Manager Window bleeds off L&R Margins

### ISSUE THREAD

**Issue by BigHairyNScary** [FontManager/font-manager#101]
I've just installed Linux for the first time (Mint Cinn).
Searching for ways to deal with fonts, I installed Font Manager. 

Problem: no matter which window in the program is open, the text bleeds off the left and right margins. For example, on the opening page I read "stem" and "er" at the top of the left column and "atagories" at the bottom of the left column.

Adjusting the size of the window has no effect.

**Comment by BigHairyNScary** [comment]
![Screenshot from 2019-11-03 16-31-10](https://user-images.githubusercontent.com/57324014/68093965-ad533780-fe58-11e9-9ff3-848dfba9371d.png)

**Comment by JerryCasiano** [comment]
Have you tried adjusting the size of the sidebar pane?

**Comment by JerryCasiano** [comment]
Also, that looks like a pretty outdated version of the application.

Just FYI
