### ISSUE TITLE
Support for plural forms

### ISSUE THREAD

**Issue by prokoudine** [FontManager/font-manager#103]
Currently, lib/vala/gtk/CellRenderer.vala:88 uses a hardcoded count of items where anything above 1 is plural. This works in English with its two plural forms, yet fails in other languages where there are 3, 4, and even more plural forms. Thus translations appear 'broken' from the grammar point of view.

Here is a similar report for another project also written in Vala, with patches you could look at: https://github.com/baedert/corebird/issues/289.

**Comment by JerryCasiano** [comment]
Thanks for pointing this out.

If you run across others please let me know, I'm sure I've screwed this type of thing up in more than one place.

**Comment by PF4Public** [comment]
Shame on me, I didn't notice this while editing ru.po :)

**Comment by prokoudine** [comment]
@PF4Public, I'm still unsure if zanata.org even supports plural forms. Either way, I've done enough harm there :) and will not meddle anymore. I'm glad you are around!
