### ISSUE TITLE
Barely visible tooltip

### ISSUE THREAD

**Issue by prokoudine** [FontManager/font-manager#106]
The new tooltip is white on pale grey with dark Adwaita.

![image](https://user-images.githubusercontent.com/57467/71202992-470e6100-22ae-11ea-86da-3f1f3b6ec819.png)

**Comment by JerryCasiano** [comment]
Thanks for pointing this out.

That's a bummer, I would prefer it to look like a normal tooltip but for now it's more important that it's actually readable across themes. I'll see if I can restore the tooltip look later.
