### ISSUE TITLE
I cant figure out how to change the sample text

### ISSUE THREAD

**Issue by apcrcom** [FontManager/font-manager#107]
I have been all through the interface and cant figure it out. 

 What is the secret?

**Comment by JerryCasiano** [comment]
![a](https://user-images.githubusercontent.com/11490124/71535093-6110fa80-28d1-11ea-8b99-5d2c2e4fec5e.png)
![b](https://user-images.githubusercontent.com/11490124/71535097-640beb00-28d1-11ea-89c9-26fa746a113b.png)
![c](https://user-images.githubusercontent.com/11490124/71535098-653d1800-28d1-11ea-9360-c857fe9ead36.png)

Does that help?

**Comment by JerryCasiano** [comment]
I would strongly recommend updating to the latest release for a much better experience. Not sure if that's a possiblity on MX Linux, no idea what version of Gtk+ they ship. Releases after 0.7.3 require Gtk+ 3.22 which has been out for about three years now. 

In any case, feel free to re-open if my previous response want helpful or ask any other questions you might have here.

**Comment by apcrcom** [comment]
Oh, wow. Thanks Jerry. Thats so helpful.

Much appreciated! :)

Jim

**Comment by yuuyins** [comment]
thanks very much for this app

i find this functionality to be very hidden, hard to find. i couldn't find it myself either and only now seeing the comments here i was able to find it.
