### ISSUE TITLE
Github linguist flags .h files as Objective-C

### ISSUE THREAD

**Issue by raggesilver** [FontManager/font-manager#112]
Github's linguist detects some `lib/common/*.h` header files as Objective-C (which I checked and they all seem to be just C). That makes your project appear to Github as an Objective-C project (with 59% flagged as that language).

![Screenshot from 2020-03-23 14-24-30](https://user-images.githubusercontent.com/16908491/77344540-0c372180-6d12-11ea-9f46-53bfa5041b8a.png)

I know this isn't a real issue, but some people like to browse projects by language and that may be misleading (I for one browse for C projects).

**Comment by JerryCasiano** [comment]
Thank you!

I noticed that, it bothered me a little bit but not enough to find out what my options were, didn't realize the fix was so simple. 

So, thanks a lot for fixing this.
