### ISSUE TITLE
Question about font-manager and goa-daemon

### ISSUE THREAD

**Issue by freethebit** [FontManager/font-manager#114]
Dist: ubuntu 19.10

1 - Mask goa service.
2 - Install font manager from ppa.
3 - Go to `Show Applications` -> Open font manager
4 - App is going to open somewhere where it is not possible to drag or access the exit button, at least ALT+F4 works.

Open by terminal it give me this msg: `Error calling StartServiceByName for org.gtk.vfs.GoaVolumeMonitor: Unit gvfs-goa-volume-monitor.service is masked. (g-io-error-quark, 36)`. But it opens fine. Close it, and open again by using `Show Applications` -> Open font manager and works as it should be.

yes, I masked `goa-daemon` service.

My question is why it complains about goa-service?

**Comment by JerryCasiano** [comment]
Font Manager does not have a hard dependency on any GNOME services at this time and it certainly does not require nor does it interact directly with the GNOME online accounts daemon. 

The error you're seeing in the terminal is not set / logged by font-manager and it's not something we have any control over.

So to answer your question, it doesn't.

**Comment by JerryCasiano** [comment]
You disabled something that is likely required, expected or used if available by quite a few things on your desktop. 

You can either ignore the error message since you know what caused it and it likely doesn't affect anything other than adding more noise to logs which are typically full of noise anyway.

Or you can keep digging.

Good luck if you decide to keep digging and it would be appreciated if you post your findings.

**Comment by freethebit** [comment]
well... on gnome + wayland, on command line it keep the error msg, but it works fine, no crash observed. But on gnome + x11 does keep crashing and freezing... anyway, not font-manager issue.

**Comment by JerryCasiano** [comment]
If font-manager keeps crashing and freezing, that's an issue.

That's something that was not mentioned originally.

If you can provide a trace that would be helpful.

See https://wiki.ubuntu.com/Backtrace & https://wiki.ubuntu.com/DebuggingProgramCrash

Feel free to reopen when you have more info.

Thanks.
