### ISSUE TITLE
Font-manager 0.7.7 will be available in Ubuntu 20.04 official repo

### ISSUE THREAD

**Issue by hosiet** [FontManager/font-manager#116]
Just to let you know that the Debian side worked with Ubuntu to remove the old inactive package maintainers for font-manager and got font-manager 0.7.7 into Debian Testing (main), Debian Unstable (main), Ubuntu 20.04 LTS (universe) and Debian 10 (main via `-backport` repo). The package split as well as file manager integration was kept to be the same with packages in the PPA.

I still cannot guarantee future package maintainers in Debian/Ubuntu could keep packaged font-manager up-to-date; it really depends on the activity of package maintainers (like me). In case I become inactive in the future, please reach out to the distribution side and seek help in having the inactive person replaced.

**Comment by JerryCasiano** [comment]
Thank you very much.

I appreciate you taking care of Debian users.

> I still cannot guarantee future package maintainers in Debian/Ubuntu could keep packaged font-manager up-to-date; it really depends on the activity of package maintainers (like me). In case I become inactive in the future, please reach out to the distribution side and seek help in having the inactive person replaced.

Of course, I completely understand. Thanks again.
