### ISSUE TITLE
cannot preview fonts of postscript type 1

### ISSUE THREAD

**Issue by zimtsui** [FontManager/font-manager#118]
it works fine with truetype, but fails with type 1

my system: ubuntu 20.04 / kde 5

![image](https://user-images.githubusercontent.com/31283202/80717742-cd279780-8b2b-11ea-8d5c-757bc93db703.png)
![image](https://user-images.githubusercontent.com/31283202/80717831-ec262980-8b2b-11ea-8f14-77a4937f1f30.png)

**Comment by JerryCasiano** [comment]
Support for Type 1 fonts was dropped from Pango some time ago.

Therefore, that preview is accurate as far as what you would see if you tried to use those fonts in any other Gtk application.

Unless I'm mistaken, I remember updating our help documents to match that change, I'll have to double check that.

Sorry, but the consensus seems to be that people should move on and convert those fonts to newer formats.

You can complain upstream, if you like, but unless you're willing and able to implement and maintain support for bitmap fonts yourself don't expect much.

**Comment by JerryCasiano** [comment]
Actually, I'm opening this back up until we start filtering these out completely or show a placeholder for them instead of a preview.

**Comment by zimtsui** [comment]
thanks for your reply.
im not expecting since type 1 has capability problem against all kinds of apps nowadays.
take a placeholder is a good idea.
