### ISSUE TITLE
Segmentation fault on starting up

### ISSUE THREAD

**Issue by Koxiaet** [FontManager/font-manager#119]
On my system (Void Linux 5.4, font-manager 0.7.7, Xorg) `font-manager` segfaults every time it starts up - sometimes it is able to keep on going but that is rare.

I [ran it through Valgrind](https://pastebin.com/rV9rrEZn) if it helps (although the debug symbols weren't on so I can't imagine it would be _that_ useful).

**Comment by JerryCasiano** [comment]
Sorry, I don't use Void, you'll need to help yourself by getting a proper backtrace using gdb and post that.

Otherwise, not much I can do.

I'm certainly not installing Void over a single report that is likely unique to your system.

**Comment by JerryCasiano** [comment]
I'll leave this open for a bit in case you or any other Void user wants to help troubleshoot.

**Comment by Koxiaet** [comment]
I compiled it on my system, and I could not reproduce the bug at all, even with the version in the repos and the exact same setup. I guess the Void repos just compiled it incorrectly.
