### ISSUE TITLE
Add po4a and itstool to the list of dependencies

### ISSUE THREAD

**Issue by Koxiaet** [FontManager/font-manager#120]
`po4a` and `itstool` are required to install this software (although they aren't required to build it), but it is not listed in the README.

**Comment by JerryCasiano** [comment]
I've never heard of po4a. That's not a requirement during build or installation..

I've added yelp-tools to the list since that's missing and covers the itstool dependency.

Thanks.

**Comment by Koxiaet** [comment]
@JerryCasiano Sorry, it's isn't actually po4a that's needed, it's gettext (which is one of its dependencies) and it provides msgfmt. If it isn't installed then you get a Python error saying "No such file or directory: msgfmt".

**Comment by JerryCasiano** [comment]
Yeah, I've run into that before.

I also added gettext to the list. :-)
