### ISSUE TITLE
Medium weight should sort after Regular weight

### ISSUE THREAD

**Issue by robin-a-meade** [FontManager/font-manager#121]
According to 
https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping
the weight name **Medium** should correspond to a weight of 500 and should therefore sort after **Normal** (400). 

When looking at the **Oswald** Google Font, the Medium weight appears out of order:
![image](https://user-images.githubusercontent.com/1343270/82523665-96a8c100-9ac8-11ea-9ee4-ac48492af52a.png)

**Comment by JerryCasiano** [comment]
![Oswald](https://user-images.githubusercontent.com/11490124/82554644-567f2800-9b34-11ea-8b36-67cbb4b2dac5.png)

I'm not seeing that, I pulled the latest version from git and it sorts as expected.

Run fc-scan on those files and make sure that metadata actually matches what you expect.

**Comment by robin-a-meade** [comment]
Thanks, it's working for me now.

I found something interesting: 6 months ago in commit [9253a5145f754df1d2eb110c3cf17d3161093e1d](https://github.com/google/fonts/commit/9253a5145f754df1d2eb110c3cf17d3161093e1d) the variable weight filename for Oswald was changed from `Oswald-Regular.ttf` to `Oswald[wght].ttf`



If I go to https://github.com/google/fonts/tree/master/ofl/oswald and download `Oswald[wght].ttf` from github.com to my `~/.local/share/fonts` folder, I get the behavior I described for this issue.

However, if I rename the filename to anything without the brackets, I get the correct expected behavior.

**Comment by JerryCasiano** [comment]
Huh. 

Thanks for sharing that detail, good to know.

I installed by dropping the entire Oswald folder onto the font list, so renaming of that file happened automatically and I didn't get that behaviour.

If you're just going to put fonts into the default folder, I would suggest using the application to install them that way they get renamed to something sensible and organized. You can drop files, folders and archives ( if file-roller is installed) onto the font list.

If you prefer to organize your fonts yourself, I would probably suggest just making a Fonts folder in your home directory and adding it as a source that's always enabled.

Anyway, glad you figured it out.
