### ISSUE TITLE
Compare doesn’t add the selected font variation

### ISSUE THREAD

**Issue by Moilleadoir** [FontManager/font-manager#124]
FontManager v. 7.7
Manjaro Cinnamon

When I select a font variation of Noto Sans (which has 72 variations!) to add to compare, a different variation is added. E.g if I select “SemiCondensed” (Noto Sans Semi-Condensed) and click the + button, it adds some other variation ­— right now “Noto Sans Thin Extra-Condensed”.

If I start at the top of the list of variations and methodically add each one, using the arrow key to move the selection, it adds the correct variation, but if I choose with the mouse it adds the wrong variation.

Also if I don’t actually add the fonts then the ‘real’ (hidden) selection also doesn’t move down the list.

I can’t say I’d noticed this before but it’s not just something odd about Noto Sans as it happens with fonts from a variety of other sources too.

**Comment by JerryCasiano** [comment]
Wow. That is bizarre...

There haven't been any changes to that code in a while. 

Not sure when it stopped working, more importantly not sure why but I'll workaround it for now.

Thanks for pointing this out.

**Comment by JerryCasiano** [comment]
By the way.

For certain fonts such as Noto, the font description used by the system itself may not match family+style the way one would expect. But that's ok as long as the expected font is selected and displayed.
