### ISSUE TITLE
Could I know existed supported font format?

### ISSUE THREAD

**Issue by intijk** [FontManager/font-manager#125]
Dear developers:

Do we have any plan to support woff2, is there a supported format list I could find?

**Comment by JerryCasiano** [comment]
Supported fonts are listed in help. Use the menu button to open help or press F1.

If help isn't available to you then you need to update the application.

GTK uses the Pango library to render fonts so if it's not supported by Pango it won't be shown in the application. It wouldn't make much sense to show you something your environment can't actually render.
