### ISSUE TITLE
Font Viewer don't shows up on panel

### ISSUE THREAD

**Issue by abhidesh128** [FontManager/font-manager#131]
I am using `font-manager` package from AUR on my Arch machine. When I open Font Viewer from menu, it opens correctly, shows up on desktop, but does not show up on panel. I can't switch to Font Viewer window from another app's window. Also, `alt + tab` does not show Font Viewer. As Font Viewer's window is not treated as any other app's window, it can't be automatically focused while drag & drop. Also, there are no minimize or resize buttons in that window. It only has close button.

Is this happening only with me ? or is it not implemented yet ? If it is not implemented, it will be very helpful to implement minimize and resize buttons as well as treat Font Viewer as a seperate app. It will not cause unfocusing and malfunctioning of Font Viewer's window while switching from another app and drag & drop.

I am using cinnamon desktop.

**Comment by JerryCasiano** [comment]
> Also, there are no minimize or resize buttons in that window. It only has close button.

Utility windows typically don't have a minimize button but this depends on your window manager. We don't add or remove any buttons.

I don't know what a resize button is, not sure I've ever seen one... but the window can be resized in the usual ways.

> Is this happening only with me ?

Nope. It's probably happening to anyone using a window manager which treats utility windows this way.

> or is it not implemented yet ?

There's nothing to implement. 

Here's a screenshot from my desktop  
![GNOME](https://user-images.githubusercontent.com/11490124/94624504-998c9d00-0284-11eb-8ff2-63159e8cc60e.png)
As you can see the window has been resized, it's listed in the switcher and in the dock.

> If it is not implemented, it will be very helpful to implement minimize and resize buttons as well as treat Font Viewer as a seperate app.

No, sorry. It is what it is. A helper utility.

And there's a very good reason for that, namely that some desktop environments treat font-viewer without the utility hint in ways that are extremely annoying.
For example, when a file manager extension is installed and font-viewer is being used to quickly preview files in a folder the desktop environment might decide to send a notification every single time a new font is selected and sent to the viewer. That is not something I can live with.

That said, you can easily modify it to remove the utility hint font-viewer if you like.

[font-viewer-main-window.ui.txt](https://github.com/FontManager/font-manager/files/5302226/font-viewer-main-window.ui.txt)

Remove the .txt extension, Github won't accept all extensions, and replace the file in src/font-viewer with it then recompile.

**Comment by abhidesh128** [comment]
Ok. So ```font-viewer``` is actually a 'helper utility'. That's why it's window specs are different. To tell you frankly, I didn't know about specs and behavior of helper utilities. Your description cleared my doubts. Thank you for you support....😊

And one thing to tell you is font manager is really rocking. I love it.✌️✌️

**Comment by JerryCasiano** [comment]
Thanks for the kind words.

I'm going to close this out for now.

If I get more users with the same request maybe we can add a setting somewhere to switch it between Utility and Normal, not sure where it would go though.
