### ISSUE TITLE
Build font-manager extension for Nemo file manager on Arch

### ISSUE THREAD

**Issue by abhidesh128** [FontManager/font-manager#132]
I am using `font-manager` from AUR on my Arch system. I want to build the file manager extension of font-manager for my nemo file manager. When I read the README.md on homepage, It says that `libnemo-extension` package is required to build the extension. I can't find that package in Arch repos, also, I don't know its Arch equivalent (if any). There is no any seperate option or argument in PKGBUILD file to tell the compiler to build extension along with font-manager.

How can I build the extension ? Is there any other process to do it ? Or, am I missing something ?

**Comment by JerryCasiano** [comment]
> How can I build the extension ? 

But installing the required library and building with -Dnemo=True option.

> Is there any other process to do it ? 

No idea what you mean by this...

> Or, am I missing something ?

Well, yes libnemo-extension

Sorry, but I don't know what else to tell you.
I don't use Arch and i don't personally maintain the AUR package.

I think you'll probably have better luck asking actual Arch Linux users, maybe try their forum  or ask the maintainer on AUR itself. The maintainer is usually pretty responsive.

I'm closing this as it is not an actual issue with the application. It's a distro specific packaging issue. Not something we can resolve on our end.

Thanks.

**Comment by abhidesh128** [comment]
I found the solution and build memo extension successfully. In arch, *libnemo-extension* is already installed with the package *nemo* itself.
The problem with me was I couldn't find that library, but after some research I found it.

**Comment by JerryCasiano** [comment]
Good deal. 

And thanks for updating with the solution.

Now I'll know what's up if someone else asks.
