### ISSUE TITLE
Any way to make non-installed fonts available to flatpak/snap apps?

### ISSUE THREAD

**Issue by terzag** [FontManager/font-manager#133]
Hello,
I have fonts stored in a local directory which I add to Font Manager using Preferences → Sources so that I can enable/disable them at will. The ones that are enabled are usable by applications installed in an usual way (mostly deb in my case, on Ubuntu) but not by applications installed as flatpak or snap packages.

I assume it's because FM makes the fonts available through some kind of mount point (in /run/user) that can't be accessed by flatpaks/snaps because of their confinement.

Installing the fonts (in ~/.local/share/fonts) makes them available to these apps but it's not really convenient for me, as I manage hundreds of fonts which I need to enable only when working on specific projects.

Is there a way to overcome that situation and have fonts enabled in FM but not installed usable by flatpak/snap apps?

Using FM 0.7.8 from the Ubuntu 20.10 repos. Tried the flatpak version from Flathub with no difference.

EDIT: someone on a forum pointed me to a possible solution for flatpak apps: using Flatseal to manage permissions, it's possible to add **xdg-config/fontconfig** in _Filesystem → Other files_ for specific apps. The fonts are then available in the configured app from their original location. It's a bit annoying that it has to be done manually for every app that needs to have access to these fonts but it works. Not sure about snap apps, though.

**Comment by JerryCasiano** [comment]
No. Unfortunately it's just one of the downsides of those packaging systems.  They have their own environment. 

I don't see any reason not to give applications, even if they're sandboxed, read only access to system and user font configuration files and directories by default. Same thing with themes, icons, etc. 

But then, what do I know? I'm not invested in these packaging formats at all so haven't even bothered to consider possible issues with doing that. The people working on them aren't stupid so I have to assume they have and there are valid reasons not to.

In any case, there really isn't anything we can do about that on our end. :-(

I'm glad you were able to find a workaround though.

**Comment by terzag** [comment]
Ok, thanks for the update.
