### ISSUE TITLE
Font Manager looses track of installed Google fonts

### ISSUE THREAD

**Issue by linuxundich** [FontManager/font-manager#136]
I installed Font Manager 0.8.0 from AUR under Arch Linux. Inside the new "Google Fonts"-Tab I can search through the fonts and install them into my system by the Button "Download Font" or "Download Family". As soon as the font is installed, the button changes it's color into red and the text says "Remove Font". I click that, the font get's deleted and the button says again "Download Font". That's what I would expect. But when I switch to another Google font, the installation status is lost. The button of the previously installed font says again "Download Font". 

Steps to reproduce:

1. Select Google Fonts from titlebar
2. Select font, e.g. Abel Normal
3. Install it by "Download Font" -> Button turns red and changes title into "Remove Font"
4. Select another font, e.g. ABeeZee
5. Select Abel Normal again -> I'm offered again to "Download Font"

Expected workflow:

1. Select Google Fonts from titlebar
2. Select font, e.g. Abel Normal
3. Install it by "Download Font" -> Button turns red and changes title into "Remove Font"
4. Select another font or go back into this dialogue later on
5. The option for all already installed Google fonts should be "Remove Font"

**Comment by JerryCasiano** [comment]
Well. This is interesting.

This issue only occurs when the code is built using --buildtype=release

My local build works exactly as you would expect but the one installed from a package behaves as you describe.

Any chance you can build from source and verify this?

**Comment by JerryCasiano** [comment]
I believe this was fixed by the commit above.

Feel free to re-open if that is not the case.
