### ISSUE TITLE
Google Fonts integration (along with libsoup and webkit) should be optional

### ISSUE THREAD

**Issue by PF4Public** [FontManager/font-manager#137]
Recent changes of integrating Google Fonts, while admittedly being a very nice feature to have, introduced a dependency on libsoup and network activity. Some users might prefer to avoid network activity and not to have a hard dependency on libsoup.

Oh, btw, does this feature also require webkit? That's a heavy dependency also.

Separating this issue from #54.

**Comment by JerryCasiano** [comment]
> Oh, btw, does this feature also require webkit? That's a heavy dependency also.

Well, if I'm not mistaken WebKit requires libsoup, actually a ton of stuff requires libsoup. But yes WebKit is required for the previews and it's definitely heavy and should be a build option.

I'll be looking into it over the weekend. Thanks for the motivation.

**Comment by JerryCasiano** [comment]
Can you try the latest commit and confirm that it works as expected please.

I'll probably do another release within the next couple of days. Hoping to sort out #135 if possible before doing so.

Thanks.

**Comment by PF4Public** [comment]
I have compiled it twice. One without webkit and another one with it. 
Without it `ldd /usr/bin/font-manager |grep -i webk` is empty and there is no G letter in the title and it works fine, as expected. With it it pulls in webkit and also works fine. `ldd /usr/bin/font-manager |grep -i webk` now shows `libwebkit2gtk-4.0.so.37 => /usr/lib64/libwebkit2gtk-4.0.so.37 (0x00007efe0a5c9000)`.

So I think, this issue is fixed now.

Thank you @JerryCasiano very much, you're awesome. If only all of the opensource projects were maintained like you do yours…

**Comment by JerryCasiano** [comment]
Thanks for verifying this. 

https://github.com/mesonbuild/meson/issues/8040

Linking the related bug report here just in case...
