### ISSUE TITLE
Lorem Ipsum preview of Google Fonts does not scale

### ISSUE THREAD

**Issue by PF4Public** [FontManager/font-manager#138]
That is obviously not 96 pt:
![image](https://user-images.githubusercontent.com/10319700/100515163-02ac6600-318b-11eb-8b7a-b6fa8b131137.png)

**Comment by JerryCasiano** [comment]
Can you test with the latest commit and see if that resolves the issue for you.

I suspect #135 is also resolved by this commit.

**Comment by PF4Public** [comment]
Seems to be fixed now:
![image](https://user-images.githubusercontent.com/10319700/100521594-b296c900-31b5-11eb-86bb-93cf9ecaf4a4.png)

But please don't do a release just yet. I'm translating new strings in Russian and some (those, that I'm capable of) in German. Will do a PR soon.

**Comment by JerryCasiano** [comment]
> But please don't do a release just yet. I'm translating new strings in Russian and some (those, that I'm capable of) in German. Will do a PR soon.

Sounds good. 

I'm going to close these issues out but will hold off on releasing.

Thanks again!
