### ISSUE TITLE
Google Fonts integration on 0.8.0 not working

### ISSUE THREAD

**Issue by paulhewson** [FontManager/font-manager#147]
Installed on ubuntu 20.04 via flatpak, the Google Fonts integration does not work, it says "network offline" when, clearly the connection is working. Is it some kind of bug or am I missing something in the settings of the application?
![Screenshot from 2020-11-29 18-56-15](https://user-images.githubusercontent.com/1159254/100549673-9b6ae080-3274-11eb-9237-0434e9de5c35.png)

**Comment by JerryCasiano** [comment]
Please file an issue at https://github.com/flathub/org.gnome.FontManager/issues

The flatpak manifest needs to allow network access.
