### ISSUE TITLE
0.8.4 Release

### ISSUE THREAD

**Issue by JerryCasiano** [FontManager/font-manager#180]
0.8.4 will be releasing soon - within a week or two depending on feedback / issues

From now on I will be opening an issue shortly before each release, 7 days at least. This should allow contributors to test, check translations, docs, etc. and hopefully prevent obvious issues from making it into an actual release.

Any and all feedback regarding current master is welcome and appreciated.

**Comment by JerryCasiano** [comment]
@PF4Public 

There were several untranslated strings that were discussed last release and though I kicked that can down the road last time, I would really like to get all issues with untranslated / unmarked strings resolved if possible.

I think the latest commit should help in that regard, but any feedback on that front is appreciated.

**Comment by PF4Public** [comment]
@JerryCasiano Thanks for pinging me. I think I'll have the time to look through translations at the weekend.

May I ask you to rephrase this: "I kicked that can down the road last time". I'm having a hard time making sense of it, sorry.

**Comment by JerryCasiano** [comment]
> May I ask you to rephrase this: "I kicked that can down the road last time". I'm having a hard time making sense of it, sorry.

Of course.

Kicking the can down the road means putting something off till later instead of just doing it now, in other words procrastinating.

> I think I'll have the time to look through translations at the weekend.

That sounds good. Thanks.

By the way, if you or anyone else needs a little more time please feel free to say so, I would much rather postpone a release to make it better than rush it out.

**Comment by PF4Public** [comment]
>I kicked that can

Well, _can_ being also a verb and _that_ being also a conjunction confused me the most :)

Your comment (with link) w.r.t. _vendor_ is most helpful, thanks, that clears the term enough. Looks like closest matches for it while translating would be something like _publisher_, _supplier_, _issuer_. I'll give it a little thinking and update all strings with that word elsewhere.

I've visited Weblate page for font-manager recently and it duly suggests some strings for editing as having inconsistent translations among UI and help files. I'll fix that as well. Cannot promise 100% translation in help though.

I'm wondering, if we should translate "Google Fonts" or leave it as is? 

Same for digits, like "4+". On one hand, most languages will have "4+" anyway, but on the other hand, I believe, that Arabic (how ironic) and related languages do have own characters for digits, let alone them being RTL…

As a side note, recently I've discovered [Variable fonts](https://en.wikipedia.org/wiki/Variable_fonts) for myself. Would be good to support them in font-manager, but at the moment, I cannot form anything specific to file a feature request. Have you had any thoughts in this regard?

**Comment by JerryCasiano** [comment]
> Cannot promise 100% translation in help though.

Most users don't even seem to realize help is even available... so while it would be nice for everything to be translated, the help documents should definitely be a much lower priority than the interface itself.

> I'm wondering, if we should translate "Google Fonts" or leave it as is?

That's an interesting question, not sure about this.

As far as digits go, I didn't even realize they were marked for translation... 

I'm thinking we should remove those since digits I think are understood everywhere, maybe we should remove Google Fonts as well? 

What do you think? 

> As a side note, recently I've discovered Variable fonts for myself. Would be good to support them in font-manager, but at the moment, I cannot form anything specific to file a feature request. Have you had any thoughts in this regard?

This is another can I've been kicking down the road for a while now... :-D

I've played around with them in the GTK font selector and my impression was that there were too many options and I'm guessing that part of the font selector will probably see very little actual use. I'm not really sure how useful exposing all those features is for most people. 

That said, I don't think adding support for this will be too difficult, we could probably even re-use some of the code from the GTK font selector. I'm not really sold on the layout the GTK font selector uses though. So figuring out how to expose this without cluttering the interface and overwhelming most users is probably the biggest challenge.

**Comment by PF4Public** [comment]
> I'm thinking we should remove those since digits I think are understood everywhere, maybe we should remove Google Fonts as well?
> 
> What do you think?

I did a quick stroll through Wikipedia articles about Google Fonts. Some articles translate (transliterate mostly), but others use it unchanged. Admittedly Wikipedia is not the best source of information, so I don't know what to say… I'd suggest excluding them from translation until someone proves it being wrong :)

> This is another can I've been kicking down the road for a while now... :-D
>So figuring out how to expose this without cluttering the interface and overwhelming most users is probably the biggest challenge.

Understandable :) Given that there is no great interest in this feature presently, you may continue kicking this can further ;)

**Comment by PF4Public** [comment]
@JerryCasiano 90 stilll wants to be translated:
https://github.com/FontManager/font-manager/blob/102d521d77c9c4809ddfeaf438cdd5fdb5e35450/po/ru.po#L2123-L2125
https://github.com/FontManager/font-manager/blob/102d521d77c9c4809ddfeaf438cdd5fdb5e35450/src/font-manager/ui/font-manager-language-filter-settings.ui#L172

**Comment by JerryCasiano** [comment]
> And probably, put this note onto other strings with "vendor"?

Missed this part - will do

**Comment by PF4Public** [comment]
Am I being overly pedantic? :D

**Comment by JerryCasiano** [comment]
> Am I being overly pedantic? :D

Nope :-)
