### ISSUE TITLE
Missing screenshots in appdata.xml

### ISSUE THREAD

**Issue by Eonfge** [FontManager/font-manager#197]
I'm having an issue with releasing 0.8.4, the manifest is outdated and the screenshots in it can't be recovered:
https://github.com/flathub/org.gnome.FontManager/pull/8

**Comment by JerryCasiano** [comment]
Interesting...

Wonder what changed.

In any case, I'll fix it this evening.

**Comment by JerryCasiano** [comment]
So that commit fixes the URL in the appdata file but now I'm wondering if it's something you can just fix in the flatpak build or if you need another release?

I'd prefer not to upload a release for this if at all possible. Would a tag work maybe?

**Comment by Eonfge** [comment]
A new tag would be enough. While at it, can you also fix the release date in the appdata.xml since it's still at 2020-07-10

**Comment by JerryCasiano** [comment]
Fixed that yesterday in 8788a250c645ea1150aee1ef589f91fef706423f

I think.

Anyway, I created a new tag just now. Let me know if it's good to go now.

Thanks again.
