### ISSUE TITLE
Can not change any option in Prefrences > Interface and Characters and Properties buttons doesn't work in main menu

### ISSUE THREAD

**Issue by lefthairynut** [FontManager/font-manager#203]
**Describe the bug**
these are the 2 seprate issues that I have.
first: you can't change any option in the Prefrences > Interface 
second: In the program when you choose a font, the Character and Properties and License buttons doesn't work. when I click on Character button, the Categories menu will hide and reappear with a very fast animation. similar issue with Properties ad Interface buttons.

**System Information**
 - OS: Arch 5.11.1-arch1-1
 - i3 wm
 - Font Manager version 0.8.4
 - Font Manager installation method [AUR](https://aur.archlinux.org/packages/font-manager/)

**Comment by JerryCasiano** [comment]
You're going to have to provide more info than this, possibly do some troubleshooting/debugging yourself. I'm obviously not going to replicate your Arch setup and since no other Arch users are complaining it's likely specific to your setup.

But let's start with terminal output, of there is any.

**Comment by lefthairynut** [comment]
command: `sudo font-mangaer`
output: 
```
(font-manager:21123): [font-manager]-CRITICAL **: 17:06:48.018: ArchiveManager.vala:61: 1 : Error spawning command line “dbus-launch --autolaunch=ffc581eaf4764808be74bd62b7bb4c3e --binary-syntax --close-stderr”: Child process exited with code 1

(font-manager:21123): dconf-WARNING **: 17:06:49.053: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=ffc581eaf4764808be74bd62b7bb4c3e --binary-syntax --close-stderr”: Child process exited with code 1
```
tha latter warning will repeate when I click on mentioned buttons.

**Comment by PF4Public** [comment]
Have you tried without sudo? What are the reasons to call it via sudo?

**Comment by lefthairynut** [comment]
when I run font-manager without sudo, the program isn't responsive and seems to be buggy. I thought maybe it needs sudo privilege for fonts in /usr/share/fonts.
like in this picture the program is running but it is invisible.
![2021-02-26_19-37](https://user-images.githubusercontent.com/30195179/109369439-3be09900-7894-11eb-810c-f04a6b3aafd9.png)

command: font-manager
output:
`(font-manager:42163): [font-manager]-CRITICAL **: 19:27:04.285: ArchiveManager.vala:61: 25 : Error calling StartServiceByName for org.gnome.ArchiveManager1: Process org.gnome.ArchiveManager1 exited with status 1`

**Comment by lefthairynut** [comment]
> Have you tried without sudo? What are the reasons to call it via sudo?

when I run font-manager without sudo, the program isn't responsive and seems to be buggy and so slow. I thought maybe it needs sudo privilege for fonts in /usr/share/fonts.
like in this picture the program is running but when I changed my workspace in i3 and then came back to the workspace that the program was running,it was invisible.
![2021-02-26_19-41](https://user-images.githubusercontent.com/30195179/109369587-caedb100-7894-11eb-871f-6512fef5d84c.png)



command: font-manager
output:
(font-manager:42163): [font-manager]-CRITICAL **: 19:27:04.285: ArchiveManager.vala:61: 25 : Error calling StartServiceByName for org.gnome.ArchiveManager1: Process org.gnome.ArchiveManager1 exited with status 1

**Comment by JerryCasiano** [comment]
Running the program as root or as any other user using sudo is completely unsupported and a terrible idea.

Completely remove ~/.cache/font-manager
Completely remove ~/.config/font-manager
Recursively chown ~/.config/fontconfig to your user.
Recursively chown ~/.local/share/fonts to your user.

Then run the application normally, i.e. not as any other user, from a terminal and post any output.

**Comment by lefthairynut** [comment]
I did all you said. still same result.
![2021-02-26_21-18](https://user-images.githubusercontent.com/30195179/109372562-15295f00-78a2-11eb-9a35-101744b48f90.png)

notice that after I installed the package, I ran it without sudo and after that It didn't run properly I ran it with sudo.

**Comment by JerryCasiano** [comment]
Well, unfortunately that's not very helpful.

Until there's evidence to the contrary I'm going to stick with my initial impression that this is something specific to your system.

I'm surprised you don't have problems with other GTK apps though...

What does localectl say?

**Comment by PF4Public** [comment]
@lefthairynut Googling "i3 gtk apps hung" gives me [this](https://bbs.archlinux.org/viewtopic.php?id=243737). Could it be related?

**Comment by lefthairynut** [comment]
> Well, unfortunately that's not very helpful.
> 
> Until there's evidence to the contrary I'm going to stick with my initial impression that this is something specific to your system.
> 
> I'm surprised you don't have problems with other GTK apps though...
> 
> What does `localectl` say?

`$ localectl`
```
System Locale: LANG=en_US.UTF-8
       VC Keymap: n/a
      X11 Layout: n/a
```
`$ locale`
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
the program was unresponsive for 25-30 seconds each time I clicked on some font.
============
this is the output of `dbus-monitor` when I lunch `font-manager`:
[http://ix.io/2R31](http://ix.io/2R31)

I have no problem with other GTK programs other than `gnome-terminal`.
`$ gnome-terminal`
```
# Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached
```
output of dbus-monitor:
[http://ix.io/2R31](http://ix.io/2R3f)

**Comment by lefthairynut** [comment]
> @lefthairynut Googling "i3 gtk apps hung" gives me [this](https://bbs.archlinux.org/viewtopic.php?id=243737). Could it be related?

I will look in to it.

**Comment by JerryCasiano** [comment]
Add [this] (

**Comment by JerryCasiano** [comment]
Also look into [this](https://bbs.archlinux.org/viewtopic.php?id=180103).

**Comment by lefthairynut** [comment]
Well, I managed to solve the `gnome-terminal`'s launching problem via installing `gnome-session` but the problem with font-manager still persist.

**Comment by JerryCasiano** [comment]
I'm going to close to close this as it is not an issue with the application so nothing we can fix on our end.

Launching the application using sudo and dbus-launch is obviously not a proper solution so I would suggest you try to figure out why it is necessary on your system and not others.
