### ISSUE TITLE
Check write permission error message

### ISSUE THREAD

**Issue by netfeld** [FontManager/font-manager#204]
Using Version 0.7.3 on Linux Mint 19
First thank you for your great work!
I was running into a problem, because i was not able to enable an disabled font again. It seems to be all right - but after restart the program the font was disabled again. 

The reason was: 

The Reject.conf in ~/.config/fontconfig/conf.d/ had no write permission. Perhaps i had used the FontManager in sudo mode before and disabled a font. After that i wasn't able to enable it again.  

It would be so much easier, if there would be any kind of error message. What do you think?

Thanks, Hauke

**Comment by JerryCasiano** [comment]
I think the application should never be run using sudo. This goes for most graphical applications by the way.

No, I'm not adding code to check for this. Sorry.

That said, feel free to submit a pull request and reopen this at that time.
