### ISSUE TITLE
Build failure due to Unicode.vapi.

### ISSUE THREAD

**Issue by PF4Public** [FontManager/font-manager#208]
Following the discussion in 10171c61e68dab82608ef14cb6bb2851ad0446fa.
There was a pre-generated `lib/unicode/Unicode.vapi` file, which was recently (in the commit mentiond above) removed. This results in a weird build failure, which is hard to reproduce as it disappears on the second attempt.
Probable solutions:
* revert that commit
* determine the root cause and fix it (according to @JerryCasiano the issue could be either with build scripts or with meson itself)
An excerptf rom build log follows:
 ```
[69/119] /usr/bin/vapigen-0.48 --quiet --library=font-manager-common --directory=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font
-manager-0.8.5-build/lib/common --vapidir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/common --vapid
ir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode --vapidir=/var/tmp/portage/app-misc/font-mana
ger-0.8.5/work/font-manager-0.8.5/lib/unicode --metadatadir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/
lib/common --pkg=glib-2.0 --pkg=gio-2.0 --pkg=gdk-3.0 --pkg=gtk+-3.0 --pkg=json-glib-1.0 --pkg=libxml-2.0 --pkg=sqlite3 --pkg=Unicode-0
.8.5 --metadatadir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5/lib/common /var/tmp/portage/app-misc/font-manag
er-0.8.5/work/font-manager-0.8.5-build/lib/common/FontManager-0.8.5.gir /var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-
0.8.5-build/lib/unicode/Unicode-0.8.5.gir /var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5/lib/common/font-manager-
common.vala
FAILED: lib/common/font-manager-common.vapi
/usr/bin/vapigen-0.48 --quiet --library=font-manager-common --directory=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-
0.8.5-build/lib/common --vapidir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/common --vapidir=/var/t
mp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode --vapidir=/var/tmp/portage/app-misc/font-manager-0.8.5
/work/font-manager-0.8.5/lib/unicode --metadatadir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/commo
n --pkg=glib-2.0 --pkg=gio-2.0 --pkg=gdk-3.0 --pkg=gtk+-3.0 --pkg=json-glib-1.0 --pkg=libxml-2.0 --pkg=sqlite3 --pkg=Unicode-0.8.5 --me
tadatadir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5/lib/common /var/tmp/portage/app-misc/font-manager-0.8.5/
work/font-manager-0.8.5-build/lib/common/FontManager-0.8.5.gir /var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-bui
ld/lib/unicode/Unicode-0.8.5.gir /var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5/lib/common/font-manager-common.vala
error: Package `Unicode-0.8.5' not found in specified Vala API directories or GObject-Introspection GIR directories
[70/119] /usr/bin/vapigen-0.48 --quiet --library=Unicode-0.8.5 --directory=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode --metadatadir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode --pkg=glib-2.0 --pkg=pango --pkg=gdk-3.0 --pkg=gtk+-3.0 --metadatadir=/var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5/lib/unicode /var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode/Unicode-0.8.5.gir
ninja: build stopped: subcommand failed.
```

Also here: PF4Public/gentoo-overlay#81

**Comment by scottfurry** [comment]
Some Google-Fu that seems relevant to the discussion:
https://github.com/mesonbuild/meson/issues/1195
https://gitlab.gnome.org/GNOME/gimp/-/issues/5400

**Comment by JerryCasiano** [comment]
@scottfurry 

Thanks for linking that Meson issue it gives me a couple things to check.

In our case the Unicode vapi is internal, it's generated during the build process.

The strange thing is the build succeeds 99.something percent of the time which seems to suggest that the meson.build files are probably correct or very close to it. 

Every now and then it attempts to build things which depend on that file before it's actually generated though.

A big problem here is... How do I know if I fixed it? :-/

**Comment by PF4Public** [comment]
I remember having a similar issue way before and IIRC it manifests once and only once at version change, so I did downgrade font-manager a number of times to 0.8.4 and then rebuilt 0.8.5 again, but it does not fail anymore. Unless we manage to find a way to reproduce it, proper fixing would be nearly impossible.

Wait a minute. I havent yet compiled it on different machine… And it fails predictably. 

@JerryCasiano I'll attach the full build log, please have a look and compare to yours, could it be that you may spot the difference? Different order of compilation? Build flags passed to meson/ninja?
[build.log](https://github.com/FontManager/font-manager/files/6189834/build.log)

The only reliable way of reproducing this atm is to try and compile font-manager in a clean chroot.

**Comment by JerryCasiano** [comment]
> The only reliable way of reproducing this atm is to try and compile font-manager in a clean chroot.

Cool. It failed to build in COPR also. So at least we'll know if we fix it.

> Could it be, that you should has_vapi: false for Unicode?

Not sure. If you can try it, please do. If not, I'll try it later.

**Comment by PF4Public** [comment]
Curious thing, on a machine that failed compilation I see this:
```
find . -iname "*Unicode-0.8.5*" 
./var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode/Unicode-0.8.5.metadata
./var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode/Unicode-0.8.5.gir
./var/tmp/portage/app-misc/font-manager-0.8.5/work/font-manager-0.8.5-build/lib/unicode/Unicode-0.8.5.vapi
```
It was in fact created, but somehow could not be found by vapigen. Just FYI, @JerryCasiano

**Comment by JerryCasiano** [comment]
@PF4Public 

Well, this is unfortunate... building in a clean chroot on my machine completed successfully.

Both Launchpad and COPR builds complete successfully also.  ( previous COPR build had failed for different reasons )

I can't trigger this bug. :-(

If you can reproduce somewhat consistently, can you please try the last commit to see if it makes any difference.

**Comment by PF4Public** [comment]
> If you can reproduce somewhat consistently, can you please try the last commit to see if it makes any difference.

I got this bug twice and this happend when I updated existing font-manager 0.8.4 to 0.8.5. Thus I can think of the only reliable way of reproducing it: a chroot with font-manager-0.8.4 installed. I think I have at least one clean chroot (that had never seen font-manager) so I will try cloning it a number of times and see if I could reliably reproduce this bug and then test your latest commit. That is not a difficult thing, I can definitely do it, but it involves intensive IO (while copying the whole chroot a number of times), so this will take quite some time. I'll let you know, how it goes.

**Comment by PF4Public** [comment]
Did some testing and I have a good news and a bad news :)

I managed to find a way to reliably reproduce this issue:
* create a chroot with all the dependencies
* clone it
* drop all caches
* try building font-manager
* it fails 100% times (tested 3 times in a row)

Obviously this explains why it failed first time, but succeeded on the second try. Caches were primed and the Unicode-thing had just the right amount of time to succeed.

That was the good news, like you may have already guessed. The bad news is that compiling from master with clean caches still fails the same way as it fails for 0.8.5.

I couldn't reliably reproduce this issue on my laptop while building from the latest commit: only the first attempt failed, even though I did clear caches the same way as while experimenting with chroots, so I assume there must be something left even after cleaning caches, files must be removed completely as is the case with removing the chroot and starting over.

**Comment by JerryCasiano** [comment]
@PF4Public 

I'm sorry to ask... but could you please try again with the latest commit?

I think the latest commit addresses this properly.

I kept reading through the Meson docs for the generate_vapi function and noticed it said that the dependency generated by that function is valid for use in generating other vapi files. I had previously tried this when we first switched to Meson and it didn't work for me for whatever reason but I just tried it again and it works as expected.

So in theory, adding the dependency to the generation of common.vapi should fix this issue. In theory.

**Comment by PF4Public** [comment]
> I'm sorry to ask... but could you please try again with the latest commit?

No need to sorry, helping however I can.

* =font-manager-9999 ✔️
* =font-manager-9999 ✔️
* =font-manager-9999 ✔️
* =font-manager-0.8.5 ❌
* =font-manager-9999 ✔️

**Comment by JerryCasiano** [comment]
Does that mean what I think it does?

Latest commit works everytime?

**Comment by PF4Public** [comment]
> Latest commit works everytime?

Exactly!

**Comment by JerryCasiano** [comment]
Sweet!

Thank you so much for your help with this. :-)

I'm going to close this out for now.

Not sure if should I'm going to do another release just yet... But I will if more users run into it.
