### ISSUE TITLE
Dark mode worked in 0.7.7, not in 0.8.5

### ISSUE THREAD

**Issue by jerry1970** [FontManager/font-manager#211]
On Xubuntu 20, Font Manager 0.7.7 took the system dark theme, but 0.8.5 stays white, even if I select Prefer Dark Theme.

**Comment by JerryCasiano** [comment]
How did you install the application?

**Comment by jerry1970** [comment]
Cheers for the quick reply! I wanted to upgrade but the regular repos only had 0.7.7.
I installed 0.8.5 using this:
```
flatpak install flathub org.gnome.FontManager 
``` 
I uninstalled 0.8.5, reinstalled 0.7.7 and that does have dark mode on.

**Comment by JerryCasiano** [comment]
Flatpak does not use system themes. I'm not sure how theming works on Flatpak actually.

Use the PPA if you want the newest version and system integration.

https://code.launchpad.net/~jerrycasiano/+recipe/font-manager-daily
