### ISSUE TITLE
Crash with GNOME 40

### ISSUE THREAD

**Issue by raphielscape** [FontManager/font-manager#212]
**Describe the bug**
font-manager crash with GNOME 40

**To Reproduce**
1. Upgrade to GNOME 40
2. Try opening font-manager
3. font-manager terminated with SIGTRAP

**Stacktrace**
```
(font-manager:54301): [font-manager]-CRITICAL **: 15:15:29.390: ArchiveManager.vala:61: 1 : Error spawning command line “dbus-launch --autolaunch=3898d9a3b94940fd91df780fef71956e --binary-syntax --close-stderr”: Child process exited with code 1

(font-manager:54301): GLib-GIO-ERROR **: 15:15:29.437: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
```

**System Information**
 - OS: Arch Linux
 - Desktop Environment: GNOME 40.0.0
 - Font Manager version: 0.8.5
 - Font Manager installation method: AUR

**Comment by PF4Public** [comment]
Did it produce any interesting output in dmesg?

**Comment by JerryCasiano** [comment]
@raphielscape 

I think I'm going to need your help on this one, I don't plan on updating my system just yet...

If you could build from the latest commit and verify it fixes the crash I can tag a new release.

**Comment by raphielscape** [comment]
> @raphielscape
> 
> I think I'm going to need your help on this one, I don't plan on updating my system just yet...
> 
> If you could build from the latest commit and verify it fixes the crash I can tag a new release.

Can confirm that latest commit fixed the crash

**Comment by JerryCasiano** [comment]
I've tagged a new release. If possible, please flag the package as out of date so the maintainer gets notified.

Thanks for reporting this and verifying the fix.
