### ISSUE TITLE
Some Desktop Settings do not work with GNOME 40

### ISSUE THREAD

**Issue by jtojnar** [FontManager/font-manager#215]
**Describe the bug**
https://github.com/FontManager/font-manager/commit/7927ca9c67e17fc6444e2a5dd5a6229f2a14e3b2 fixed the crash but since the moved settings were also renamed, they are skipped as not present in either schema:

```
[font-manager]-Message: 03:01:01.826: Desktop.vala:122: Ignoring deprecated settings key : antialiasing
[font-manager]-Message: 03:01:01.827: Desktop.vala:122: Ignoring deprecated settings key : rgba-order
[font-manager]-Message: 03:01:01.827: Desktop.vala:122: Ignoring deprecated settings key : hinting

(font-manager:2036615): [font-manager]-CRITICAL **: 03:01:01.827: font_manager_desktop_preferences_generate_options_list: assertion '_tmp100_ != NULL' failed
```

**To Reproduce**
1. Run GNOME 40
2. Open preferences
3. Switch to desktop
4. See that the draggers are missing

**Screenshot**
![Screenshot from 2021-04-16 03-01-27](https://user-images.githubusercontent.com/705123/114957143-ae1b3600-9e60-11eb-9484-8f3c81533866.png)

**Expected behavior**
All settings should be shown as in previous GNOME versions.

**System Information**
 - OS: NixOS unstable
 - Desktop Environment GNOME
 - Font Manager version 0.8.6
 - Font Manager installation method manually tweaked Distribution package

**Additional context**
The settings were moved in the schemas here:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/merge_requests/199/diffs → https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/merge_requests/38/diffs

Also, without the now-useless gnome-settings-daemon schemas installed, the desktop pane is completely empty but still shown in the sidebar.

**Comment by JerryCasiano** [comment]
@jtojnar 

I would appreciate it if you could build from master and confirm whether the changes work for you or not.

**Comment by jtojnar** [comment]
Thanks for the quick fix. Unfortunately, it is not enough:

```
(font-manager:2095435): GLib-GIO-CRITICAL **: 04:35:49.300: g_settings_get_enum: assertion 'G_IS_SETTINGS (settings)' failed

(font-manager:2095435): GLib-GObject-WARNING **: 04:35:49.300: invalid (NULL) pointer instance

(font-manager:2095435): GLib-GObject-CRITICAL **: 04:35:49.300: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

Probably because it is still querying the xsettings:

https://github.com/FontManager/font-manager/blob/b28f325d7951a66ebf1a2a432ee09fd22048a033/src/font-manager/preferences/Desktop.vala#L159

**Comment by jtojnar** [comment]
That was without g-s-d schemas installed. With them it crashes with:

```
(font-manager:2095635): GLib-GIO-ERROR **: 04:38:37.301: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'font-antialiasing'
```

**Comment by JerryCasiano** [comment]
@jtojnar 

Thanks.

I think, I hope, the latest commit fixes both those issues.

**Comment by jtojnar** [comment]
That seems to fix the issue. Thank you very much.

**Comment by JerryCasiano** [comment]
@jtojnar 

Thank you for reporting this and confirming the fix.

**Comment by jtojnar** [comment]
Yes, backporting the commits is not a problem for us.

Hilariously, running the app on system that has the old schemas (e.g. Ubuntu) displays the configs twice:

![Screenshot from 2021-04-16 13-41-45](https://user-images.githubusercontent.com/705123/115019778-ef8bff80-9eb9-11eb-8c9e-89253fe5b34e.png)

and complains:

```
(font-manager:2133148): Gtk-WARNING **: 13:41:25.781: Attempting to add a widget with type FontManagerSubpixelGeometry to a GtkRevealer, but as a GtkBin subclass a GtkRevealer can only contain one widget at a time; it already contains a widget of type FontManagerSubpixelGeometry

(font-manager:2133148): Gtk-WARNING **: 13:41:25.781: Attempting to add a widget with type GtkRevealer to a container of type GtkListBoxRow, but the widget is already inside a container of type GtkListBoxRow, please remove the widget from its existing container first.
```

But there is probably no good way to solve this, since apps built by Nix will [load stuff from the new settings](https://gitlab.gnome.org/GNOME/gtk/-/commit/4e02e292a67044b81350c6041a65648143bd4eec) (we wrap GUI apps in a way that they are self-contained with regards to the GSettings schemas they need) and the rest of apps on Ubuntu will use the old settings. I mean, writing can be solved by writing to both but it is not clear to me what should be displayed on the Scale widget when the both values are different. And running graphical apps from Nix on Ubuntu is not that common so I am not sure this is even worth solving when the next Ubuntu release will switch to GNOME 40 anyway.

**Comment by JerryCasiano** [comment]
@jtojnar 

Actually, I *think* we can resolve that pretty easily. 

It occurred that to me after the last commit that if the interface schema contains the new keys we should just drop the xsettings schema even if it's actually there.

I'll do that this evening and ping you, hopefully you don't mind me using you to test. I haven't updated yet.

**Comment by JerryCasiano** [comment]
@jtojnar 

I think the last commit might work properly in both situations. If you can test when you get a chance that would be great.

Thanks.

**Comment by jtojnar** [comment]
Thanks, tested in the following situations:

| g-s-d + g-d-s 3.38 | g-s-d 40 | g-d-s 40 | screenshot |
|--------------------|----------|----------|------------|
| ❌                  | ❌        | ❌        | empty      |
| ❌                  | ❌        | ✅        | full       |
| ❌                  | ✅        | ❌        | empty      |
| ❌                  | ✅        | ✅        | full       |
| ✅                  | ❌        | ❌        | full       |
| ✅                  | ✅        | ✅        | full       |

![empty](https://user-images.githubusercontent.com/705123/115095891-3a8e2d00-9f23-11eb-9617-b30397aded53.png)
![full](https://user-images.githubusercontent.com/705123/115095887-395d0000-9f23-11eb-906f-0cf63c592f47.png)

**Comment by JerryCasiano** [comment]
@jtojnar 

Whoa! Thanks.

So it seems we have some improvement. That looks like it should cover most sensible configurations?

The thing that's bothering me is that you have a blank page instead of the placeholder that should be there if there are no entries. I need to look into that.

**Comment by JerryCasiano** [comment]
@jtojnar 

Thank you so much for all your help with this.
