### ISSUE TITLE
Substitutions target families missing after closing font-manager

### ISSUE THREAD

**Issue by raphielscape** [FontManager/font-manager#216]
**Describe the bug**
After configuring font substitutions, the target font configurations lost after closing the app

**To Reproduce**
1. Configure Font Substitutions
2. Save
3. Close font-manager
4. Relaunch and go to the Font Substitutions page

**Expected behavior**
Font Family Substitutions settings retained after relaunch.

**Screenshots**
![Screenshot from 2021-04-18 04-43-15](https://user-images.githubusercontent.com/23637682/115127426-9c709480-a000-11eb-9431-8c869bbee1cd.png)

**System Information**
 - OS: Arch Linux
 - Desktop Environment: GNOME 40
 - Font Manager version 0.8.6
 - Font Manager installation method: AUR

**Comment by JerryCasiano** [comment]
If you could build from the latest commit and verify that it fixes your issue that would be great.

**Comment by raphielscape** [comment]
![Screenshot from 2021-04-18 13-14-52](https://user-images.githubusercontent.com/23637682/115136156-15470f00-a048-11eb-8079-56d67bc82eb8.png)

The latest commit fixed it, Thanks!

Closing the issue
