### ISSUE TITLE
Column is too narrow

### ISSUE THREAD

**Issue by freder** [FontManager/font-manager#217]
**Describe the bug**

the font name column is way too narrow for how much space there is available

**To Reproduce**
- activate wide mode
- resize the center column

**Expected behavior**
the column should take up the available horiz. space. perhaps you could also make it resizable by the user.

**Screenshots**
![Screenshot from 2021-04-24 13-15-01](https://user-images.githubusercontent.com/724844/115956936-f2ad6e00-a4ff-11eb-9219-e8221874d16a.png)

**System Information**
 - OS: manjaro
 - Desktop Environment: gnome
 - Font Manager version: 0.8.6
 - Font Manager installation method: official repositories (community)

**Comment by JerryCasiano** [comment]
Rendering the family name in full when space is limited creates an even worse result with the rightmost column simply getting cut off as pointed out in https://github.com/FontManager/font-manager/issues/210#issuecomment-810391132 

In any case, I don't really consider a bit of extra white space a bug but if you or anyone else is inclined to work on this, great, I'm happy to review a pull request. Feel free to re-open at that time.

**Comment by PF4Public** [comment]
@freder If you're still interested, there might be a solution to this issue: https://github.com/FontManager/font-manager/issues/210#issuecomment-1046289235
