### ISSUE TITLE
font-manager doesn't detect fonts in xorg-fonts-100dpi package

### ISSUE THREAD

**Issue by asgharam** [FontManager/font-manager#218]
font-manager can't detect xorg-fonts although they're installed and usable.(fc-list will show them)
I installed the fonts with xorg-fonts-100dpi in the arch repository. these fonts are compressed and have .pcf extension.(.pcf.gz)
I tried :

1. removing font-manager directory both in .config and .cache directories.
2. completely uninstalling and removing the related directory in .config and .cache  and reinstalling.
3. to manually install the fonts with font-manager with add button in the window but the font-manager doesn't show any fonts. 

So I suspect that these type of fonts are not supported but I opened an issue about it to prevent wasting time of others.
font-manager 0.8.6
arco linux 5.12.2-arch1-1

**Comment by JerryCasiano** [comment]
> font-manager can't detect xorg-fonts although they're installed and usable.(fc-list will show them)

Usable? Sorry, but fc-list listing them doesn't count as usable. 

Name one GTK application where these fonts are listed and rendered correctly and we can say that they are usable.

 > So I suspect that these type of fonts are not supported 

Support for bitmap fonts was dropped by Pango quite a while ago.

The help documents which can be accessed from the application menu or by hitting F1 list supported filetypes.

> but I opened an issue about it to prevent wasting time of others.

Huh.

**Comment by asgharam** [comment]
I didn't know they don't get rendered correctly in GTK application. There was a font called Helvetica which I liked it and it was in this package and I wanted to use it just for web.

> but I opened an issue about it to prevent wasting time of others.

There was no pun intended and I appreciate the effort you guys putting! Have a good one!

**Comment by JerryCasiano** [comment]
> There was a font called Helvetica which I liked it and it was in this package and I wanted to use it just for web.

I doubt that would work anyway.

You can convert the old fonts to ttf or otf but I doubt you'll like the result. You're much better off finding the same font in ttf, otf or woff version.

> There was no pun intended and I appreciate the effort you guys putting! Have a good one!

I know. It just sounded funny so figured I'd give you a hard time about it.

Take care and on a serious note if you do rub into any other issues don't hesitate to ask here. ;-)

**Comment by asgharam** [comment]
The font worked but the downside is that you can't set the exact font-size and have to give it something like "large" "larger" "small" as the value of font-size.
Cheers!
