### ISSUE TITLE
Hang/crash trying to display big list of fonts

### ISSUE THREAD

**Issue by tudo75** [FontManager/font-manager#223]
I have a big fonts folder for graphics projects and font-manager hang and block all system when I try to load the long list of fonts in the main view (about 10000 fonts).
Only audio continue to work but all related to desktop environment (every gui) stop so I must force shutdown using the power button.

**System Information**
 - OS: Linux Mint 20.2 Uma
 - Desktop Environment XFCE
 - Font Manager version 0.8.6.202107090416~ubuntu20.04.1
 - Font Manager installation method PPA
 - All packages are up to date

**stack trace**
===================================================================
 Info                                                              
===================================================================
           PID: 755279 (font-manager)
           UID: 1000 (nick)
           GID: 1000 (nick)
        Signal: 11 (SEGV)
     Timestamp: Sat 2021-07-17 15:57:57 CEST (23h ago)
  Command Line: font-manager
    Executable: /usr/bin/font-manager
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (nick)
       Boot ID: d0cc85093c5d42ec9d5b9e217016c00d
    Machine ID: c4f2d44acf3c4564bf5a66409c42613f
      Hostname: MINT-NEMO
       Storage: /var/lib/systemd/coredump/core.font-manager.1000.d0cc85093c5d42ec9d5b9e217016c00d.755279.1626530277000000000000.lz4
       Message: Process 755279 (font-manager) of user 1000 dumped core.
                
                Stack trace of thread 755279:
                #0  0x00005556593a168c n/a (font-manager + 0x6268c)
                #1  0x00007fcff7fde04e g_main_context_dispatch (libglib-2.0.so.0 + 0x5204e)
                #2  0x00007fcff7fde400 n/a (libglib-2.0.so.0 + 0x52400)
                #3  0x00007fcff7fde4a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #4  0x00007fcff81f7fe5 g_application_run (libgio-2.0.so.0 + 0xe2fe5)
                #5  0x0000555659372b64 font_manager_application_main (font-manager + 0x33b64)
                #6  0x00007fcff3b190b3 __libc_start_main (libc.so.6 + 0x270b3)
                #7  0x000055565936f24e _start (font-manager + 0x3024e)
                
                Stack trace of thread 755306:
                #0  0x00007fcff3c02f24 __libc_open64 (libc.so.6 + 0x110f24)
                #1  0x00007fcff371b93f n/a (libfreetype.so.6 + 0xc93f)
                #2  0x00007fcff37230d4 n/a (libfreetype.so.6 + 0x140d4)
                #3  0x00007fcff3726402 n/a (libfreetype.so.6 + 0x17402)
                #4  0x00007fcff3726d60 FT_New_Face (libfreetype.so.6 + 0x17d60)
                #5  0x00007fcff37e7166 FcFreeTypeQueryAll (libfontconfig.so.1 + 0x19166)
                #6  0x00007fcff37e19b4 n/a (libfontconfig.so.1 + 0x139b4)
                #7  0x00007fcff37e1e0e n/a (libfontconfig.so.1 + 0x13e0e)
                #8  0x00007fcff37e202c n/a (libfontconfig.so.1 + 0x1402c)
                #9  0x00007fcff37dcce1 n/a (libfontconfig.so.1 + 0xece1)
                #10 0x00007fcff37dced5 FcConfigAppFontAddDir (libfontconfig.so.1 + 0xeed5)
                #11 0x00005556593b4748 n/a (font-manager + 0x75748)
                #12 0x00007fcff7fae0cb g_ptr_array_foreach (libglib-2.0.so.0 + 0x220cb)
                #13 0x00005556593b5912 font_manager_load_user_font_resources (font-manager + 0x76912)
                #14 0x000055565937011a n/a (font-manager + 0x3111a)
                #15 0x00007fcff8007ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #16 0x00007fcff3609609 start_thread (libpthread.so.0 + 0x9609)
                #17 0x00007fcff3c14293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 755282:
                #0  0x00007fcff3c07aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fcff7fde36e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007fcff7fde4a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #3  0x00007fcfeca5c99d n/a (libdconfsettings.so + 0xa99d)
                #4  0x00007fcff8007ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007fcff3609609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fcff3c14293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 755280:
                #0  0x00007fcff3c07aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fcff7fde36e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007fcff7fde4a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
                #3  0x00007fcff7fde4f1 n/a (libglib-2.0.so.0 + 0x524f1)
                #4  0x00007fcff8007ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007fcff3609609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fcff3c14293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 755281:
                #0  0x00007fcff3c07aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fcff7fde36e n/a (libglib-2.0.so.0 + 0x5236e)
                #2  0x00007fcff7fde6f3 g_main_loop_run (libglib-2.0.so.0 + 0x526f3)
                #3  0x00007fcff8233f8a n/a (libgio-2.0.so.0 + 0x11ef8a)
                #4  0x00007fcff8007ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
                #5  0x00007fcff3609609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fcff3c14293 __clone (libc.so.6 + 0x122293)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 755279]
[New LWP 755306]
[New LWP 755282]
[New LWP 755280]
[New LWP 755281]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `font-manager'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005556593a168c in ?? ()
[Current thread is 1 (Thread 0x7fcfee28eac0 (LWP 755279))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 755279]
[New LWP 755306]
[New LWP 755282]
[New LWP 755280]
[New LWP 755281]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `font-manager'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005556593a168c in ?? ()
[Current thread is 1 (Thread 0x7fcfee28eac0 (LWP 755279))]
#0  0x00005556593a168c in  ()
#1  0x00007fcff7fde04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcff7fde400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcff7fde4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcff81f7fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x0000555659372b64 in font_manager_application_main ()
#6  0x00007fcff3b190b3 in __libc_start_main (main=0x55565936f200 <main>, argc=1, argv=0x7fffa1d727b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffa1d727a8) at ../csu/libc-start.c:308
#7  0x000055565936f24e in _start ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 755279]
[New LWP 755306]
[New LWP 755282]
[New LWP 755280]
[New LWP 755281]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `font-manager'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005556593a168c in ?? ()
[Current thread is 1 (Thread 0x7fcfee28eac0 (LWP 755279))]

Thread 5 (Thread 0x7fcfed37b700 (LWP 755281)):
#0  0x00007fcff3c07aff in __GI___poll (fds=0x7fcfe0006c30, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fcff7fde36e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcff7fde6f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcff8233f8a in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fcff8007ad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcff3609609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140531014809344, 1358616048929857475, 140735908615422, 140735908615423, 140735908615568, 140531014806592, -1349641218289836093, -1349636401008091197}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fcff3c14293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fcfedb7c700 (LWP 755280)):
#0  0x00007fcff3c07aff in __GI___poll (fds=0x55565a4160a0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fcff7fde36e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcff7fde4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcff7fde4f1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcff8007ad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcff3609609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140531023202048, 1358616048929857475, 140735908614990, 140735908614991, 140735908615136, 140531023199296, -1349640119315079229, -1349636401008091197}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fcff3c14293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fcfeca4d700 (LWP 755282)):
#0  0x00007fcff3c07aff in __GI___poll (fds=0x55565a49f6e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fcff7fde36e in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcff7fde4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcfeca5c99d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007fcff8007ad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcff3609609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140531005183744, 1358616048929857475, 140735908618286, 140735908618287, 140735908618432, 140531005180992, -1349638081889968189, -1349636401008091197}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fcff3c14293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fcfddcc3700 (LWP 755306)):
#0  0x00007fcff3c02f24 in __libc_open64 (file=0x7fcfd40a5b80 "/media/nick/DATI_1T_BLACK/Downloads/Software/DEV MATERIAL/fonts/Tutti I Miglior Fonts O Caratteri Windows Per Pc E Mac/W/woodsticks.zip", oflag=0) at ../sysdeps/unix/sysv/linux/open64.c:48
        resultvar = 18446744073709551612
        sc_cancel_oldtype = 0
        mode = 0
#1  0x00007fcff371b93f in  () at /lib/x86_64-linux-gnu/libfreetype.so.6
#2  0x00007fcff37230d4 in  () at /lib/x86_64-linux-gnu/libfreetype.so.6
#3  0x00007fcff3726402 in  () at /lib/x86_64-linux-gnu/libfreetype.so.6
#4  0x00007fcff3726d60 in FT_New_Face () at /lib/x86_64-linux-gnu/libfreetype.so.6
#5  0x00007fcff37e7166 in FcFreeTypeQueryAll () at /lib/x86_64-linux-gnu/libfontconfig.so.1
#6  0x00007fcff37e19b4 in  () at /lib/x86_64-linux-gnu/libfontconfig.so.1
#7  0x00007fcff37e1e0e in  () at /lib/x86_64-linux-gnu/libfontconfig.so.1
#8  0x00007fcff37e202c in  () at /lib/x86_64-linux-gnu/libfontconfig.so.1
#9  0x00007fcff37dcce1 in  () at /lib/x86_64-linux-gnu/libfontconfig.so.1
#10 0x00007fcff37dced5 in FcConfigAppFontAddDir () at /lib/x86_64-linux-gnu/libfontconfig.so.1
#11 0x00005556593b4748 in  ()
#12 0x00007fcff7fae0cb in g_ptr_array_foreach () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00005556593b5912 in font_manager_load_user_font_resources ()
#14 0x000055565937011a in  ()
#15 0x00007fcff8007ad1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007fcff3609609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140530756105984, 1358616048929857475, 140735908617582, 140735908617583, 140735908617728, 140530756103232, -1349534518417301565, -1349636401008091197}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#17 0x00007fcff3c14293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fcfee28eac0 (LWP 755279)):
#0  0x00005556593a168c in  ()
#1  0x00007fcff7fde04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcff7fde400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcff7fde4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcff81f7fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x0000555659372b64 in font_manager_application_main ()
#6  0x00007fcff3b190b3 in __libc_start_main (main=0x55565936f200 <main>, argc=1, argv=0x7fffa1d727b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffa1d727a8) at ../csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {93829352777328, 1358616048929857475, 93829352321568, 140735908620208, 0, 0, -1358532689757741117, -1349635705351577661}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7fffa1d727b8}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#7  0x000055565936f24e in _start ()
#0  0x00005556593a168c in  ()
#1  0x00007fcff7fde04e in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcff7fde400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcff7fde4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcff81f7fe5 in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#5  0x0000555659372b64 in font_manager_application_main ()
#6  0x00007fcff3b190b3 in __libc_start_main (main=0x55565936f200 <main>, argc=1, argv=0x7fffa1d727b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffa1d727a8) at ../csu/libc-start.c:308
#7  0x000055565936f24e in _start ()

**Comment by JerryCasiano** [comment]
There are a couple issues with this report:

- PPA package installed on an unsupported distribution
- No debug symbols installed

Installing a PPA package on something which, while close, isn't actually Ubuntu is worth a try but it's definitely not something we're going to try to "fix" if it doesn't work right.

Traces generated without debug symbols installed not only for the application but for the libraries it uses are not very useful in most cases.

Displaying a large list of fonts isn't normally an issue for the application. While the application isn't designed with massive font collections in mind I regularly test using 7500 fonts sourced from different folders. Large amounts of sourced or installed font files will definitely cause a performance hit at application start up and when using the waterfall preview mode but other than that should not be an issue.

I suspect the crash is happening inside of Fontconfig and I'm guessing the font folder you've added as a source contains a variety of different file types along with a large amount of font files of varying quality. 

You should try using a folder with only font files as a source. 

If that doesn't help, you need to install the application from source using the latest commit and verify the issue persists. If that is the case then please install [debug symbols](https://wiki.ubuntu.com/Debug%20Symbol%20Packages) before generating traces and opening a new issue. Also, if possible, please attach any traces or other debug information to the issue rather than pasting inline as it makes the issue less readable, more difficult to interact with since I now have to scroll and scroll and scroll to respond.

I'm closing this now. 

Feel free to ask any question you may have here and please feel free to open a new issue once you have completely ruled out unrelated files in font folders causing Fontconfig to crash and application library mismatch due to installing package intended for a different distribution.

Thanks.
