### ISSUE TITLE
Enable/disable single font hard linking it

### ISSUE THREAD

**Issue by tudo75** [FontManager/font-manager#225]
Hi, it's possible to add option to enable/disable (activate/deactivate system wide visibility) single font or family instead of the whole source folder by creating an hard link?

**Comment by JerryCasiano** [comment]
Is it possible? Sure.

Why would we do this though? Not only does it sound nasty but it doesn't even make much sense.

Please explain why this would be better than simply installing/removing the font?

We already make this super easy by allowing you to right click and install sources fonts. What am I missing?
