### ISSUE TITLE
Version 0.8.7 dumps core on FreeBSD 13.0-RELEASE

### ISSUE THREAD

**Issue by ehaupt** [FontManager/font-manager#233]
**Describe the bug**
Core dump when starting font-manager 0.8.7 on FreeBSD 13.0-RELEASE amd64. Works fine with 0.8.6.

**To Reproduce**
1. Install FreeBSD 13.0-RELEASE amd64
2. Get the ports tree
`git clone https://git.FreeBSD.org/ports.git /usr/ports`
3. Apply this patch to `/usr/ports/x11-fonts/font-manager`
[font-manager-port-update.patch.txt](https://github.com/FontManager/font-manager/files/6906673/font-manager-port-update.patch.txt)
4. Build font-manager via ports
```
cd /usr/ports/x11-fonts/font-manager
make install clean
```
5. Setup an X environment of your choice and start font-manager as user
6. Observe the core dump
```
(font-manager:26097): GLib-GIO-ERROR **: 11:40:43.012: Settings schema 'org.gnome.FontManager' does not contain a key named 'max-waterfall-size'
Trace/BPT trap (core dumped)
```
 

**Expected behavior**
Don't core dump.

**System Information**
 - OS: FreeBSD 13.0-RELEASE amd64
 - Desktop Environment XFCE in my case
 - Font Manager version 0.8.7
 - Font Manager installation method FreeBSD ports

**Comment by JerryCasiano** [comment]
This is a packaging or build issue.

That error means the schema was not installed correctly or was not compiled after installation.

Things to try:

Grep the schema file for waterfall and ensure it contains that key. 

If it does, great, as root run

`glib-compile-schemas /usr/share/glib-2.0/schemas`

Or whatever the equivalent is on a FreeBSD system and try again.

**Comment by ehaupt** [comment]
Thank you, after running
```
glib-compile-schemas /usr/local/share/glib-2.0/schemas
```
the program starts as expected.

**Comment by JerryCasiano** [comment]
Your welcome. 

I'm not really familiar with how ports work but it should run that command after installation. Typically Linux packages will use some type of post script to do so.

If you do run into any other problems, don't hesitate to ask here or open another issue.

**Comment by ehaupt** [comment]
> I'm not really familiar with how ports work but it should run that command after installation. Typically Linux packages will use some type of post script to do so.

There is also a macro in the ports framework ports that I wasn't aware of until now. Just for completeness:

```
GLIB_SCHEMAS=   org.gnome.FontManager.gschema.xml \
                org.gnome.FontViewer.gschema.xml
```
