### ISSUE TITLE
Tests not included in release tarball

### ISSUE THREAD

**Issue by knuxify** [FontManager/font-manager#238]
**Describe the bug**
The release tarball provided on the release page does not contain the source code for tests.

**To Reproduce**
1. Go to [GitHub releases page](https://github.com/FontManager/font-manager/releases)
2. Download font-manager-(version).tar.xz
3. Extract the archive

The "tests" directory is not present.

**Expected behavior**
The "tests" directory is present, and contains the source code for tests.

**Additional context**
I'm working on an Alpine Linux package for font-manager. Adding tests to the check function is usually required when making Alpine Linux packages (generally checks are only disabled if upstream doesn't have any tests at all or if the tests are known to be bad).

In this case an alternative would be to download the tag source code directly rather than relying on the release tarballs, but that isn't really ideal.

**Comment by JerryCasiano** [comment]
>  (... if the tests are known to be bad).

Which is pretty much the case... I mean, I don't know that they're bad but they're certainly pointless in the current state.

I can simply delete the directory if that makes your life easier.

Let me know. I can push that change tonight if you like.

**Comment by knuxify** [comment]
> > (... if the tests are known to be bad).
> 
> Which is pretty much the case... I mean, I don't know that they're bad but they're certainly pointless in the current state.

By "the tests are bad" I mostly meant "the tests don't work/need some platform-specific stuff that only works on other distros/doesn't test the right thing". But if the tests were pointless as they were, it should be fine to remove them.

Thanks for the quick response!

**Comment by JerryCasiano** [comment]
Your welcome.

If you do run into any other packaging issues, please let me know so we can get them taken care of at the source 

Thanks.
