### ISSUE TITLE
Flatpak: Compilation issue GCC 11 with Vala 0.54.1

### ISSUE THREAD

**Issue by Eonfge** [FontManager/font-manager#240]
**Describe the bug**
the application won't compile the latest version of the GNOME Runtime. 

**To Reproduce**
The easiest way to see this in action, is by looking at the Flathub logs:
https://github.com/flathub/org.gnome.FontManager/pull/14

**Local log**
[FontManagerLog.txt](https://github.com/FontManager/font-manager/files/7261988/FontManagerLog.txt)

**System Information**
 - Flatpak 1.10
 - GNOME 41
 - Font Manager 0.8.7

**Comment by JerryCasiano** [comment]
Can you try the latest commit to see if it fixes this issue?

**Comment by Eonfge** [comment]
That fixes it! Cool.

I'll make sure to update the package runtime when you make a new release. No hurry though, right now the package is using GNOME 40 and that's supported for another half a year.
