### ISSUE TITLE
Scrolling issues in Google Fonts preview section

### ISSUE THREAD

**Issue by abhidesh128** [FontManager/font-manager#243]
In the Google Fonts font preview section, scrolling does not work. Both vertical and horizontal scroll bars just seem to be dead.

Version : 0.8.7
Distribution : MX Linux 21 "Wildflower"
GTK+ Version : 3.24.24
Base Distro : Debian Bullseye.

![Screenshot_2021-11-05_11-38-14](https://user-images.githubusercontent.com/56992370/140466994-67c8bb08-bbf3-426b-a1cd-4f3ba5314471.png)

**Comment by JerryCasiano** [comment]
I was only able to reproduce this when attempting to scroll using a touchscreen. Other devices work as expected for me.

Is that the case? If it is the latest commit should resolve that issue.

**Comment by abhidesh128** [comment]
Yes. I am using `font-manager` on laptop and was trying to hold scroll bars with touch pad. Later, I enabled scrolling gestures in settings and scrolling started working. So the issue was limited to touch events.

**Comment by JerryCasiano** [comment]
Sounds like this is resolved. Thanks.
