### ISSUE TITLE
New typeface is added in default size when in compare mode

### ISSUE THREAD

**Issue by spezialspezial** [FontManager/font-manager#246]
Hey, small issue,

when in compare mode, which I love dearly, I have the font size, slider on the bottom, turned all the way up. Now when adding a new typeface it appears in the tiddly tiny default size. Good sir, if you would note that small issue of this wonderful computer program I would be most happy.

**To Reproduce**

1. Go into compare mode
2. Add a first typeface (would be nice if this would work with a double click)
3. Turn up the font size to volume 11
4. Add another typeface, it's compare after all
5. Try to find the typeface on the right side and notice it's small size
6. Wiggle the size slider to have it pop in place

**Expected behavior**
New typeface gets added in the size I have commanded

**Screenshots**
![issue_new_type_is_small](https://user-images.githubusercontent.com/75758219/142664252-6c14123d-255e-4692-893d-9a76fcf2cac0.jpg)

**System Information**

 - OS: Ubuntu 20.04, GNOME via flatpak
 - Font Manager 0.8.7

**Comment by JerryCasiano** [comment]
Unfortunately I can not duplicate this here.

Also, is there a reason you are using the Flatpak version rather than the PPA version?

**Comment by spezialspezial** [comment]
Trusting is good but sandboxing is better. It's supposed to be less hassle too, not quite there yet though.

**Comment by spezialspezial** [comment]
With the PPA version I can't replicate this either

**Comment by JerryCasiano** [comment]
> Trusting is good but sandboxing is better. 

That assumes that the sandbox actually works correctly.

> It's supposed to be less hassle too, not quite there yet though.

I don't agree with the less hassle thing. It certainly seems like more of a hassle to me, personally.

I definitely agree that it's not quite there yet.

> With the PPA version I can't replicate this either

I'm going to close this for now as it seems this is only the case for Flatpak. 

I'm not really inclined to spend much time trying to diagnose this at this time.

**Comment by spezialspezial** [comment]
Fair enough, it's a lot of work.
