### ISSUE TITLE
Crash on Google Fonts

### ISSUE THREAD

**Issue by spezialspezial** [FontManager/font-manager#247]
**Describe the bug**
In manage mode, clicking G for Google Fonts crashes the app after a short while. Crash is not instant, possibly networking related. Not sure if there is a crash dump getting saved, app just disappears.

**To Reproduce**
1. Open app
2. Select manage
3. Click the G
4. Wait 5 seconds

**System Information**
 - OS: Ubuntu 20.04, GNOME, via flatpak
 - Font Manager 0.8.7

**Comment by PF4Public** [comment]
Do you have anything in dmesg?

**Comment by spezialspezial** [comment]
traps: pool-font-manag[117241] trap int3 ip:7f9ac10ef0d7 sp:7f9a437faeb0 error:0 in libglib-2.0.so.0.6800.3[7f9ac10b0000+8d000]

**Comment by spezialspezial** [comment]
For a split second I just saw a big network error panel just before disappearing

**Comment by spezialspezial** [comment]
Also `GoogleFonts.vala:147: 7 : Unable to create socket: Too many open files`

**Comment by spezialspezial** [comment]
Maybe try to replicate with network disabled

**Comment by JerryCasiano** [comment]
I can not duplicate this issue either.

Please completely remove the Flatpak version and use the PPA version for testing purposes.

Please report back whether or not you can duplicate these issues using the PPA version.

**Comment by spezialspezial** [comment]
With the regular install I can't replicate either. I turned ethernet off and it seems it can tell exactly why it can't connect, so maybe not the same premise as another network error. I did have another very old install before that I could not deinstall via Ubuntu Software. Just to complicate things and make debugging more fun. :)

**Comment by spezialspezial** [comment]
The Google Fonts feature is very nice btw

**Comment by JerryCasiano** [comment]
I can't duplicate this with the Flatpak version either.

Unfortunately the Flatpak version simply gives me an empty view when Google Fonts is selected, no crash though.

I'm going to leave this open for a bit in case I get bored and end up looking into it. But as before I may end up closing without any resolution. :-/

Please don't let this deter you from reporting issues you encounter in the future though.

**Comment by Hunanbean** [comment]
None of the fonts from google show up, but the crash has stopped. three things i have done.
Allowed full sandbox permissions to the app, then removed them.
Rebooted. 
Added the line --persist=path to file system permissions, then removed it.
I am no longer crashing while trying to access google fonts, but no google fonts show up. infact, it is not even triggering my firewall. It is as though the app is not trying to connect to the internet anymore. (sandbox permission is allowing it to connect to internet, and it was trying to connect back when it was crashing)

**Comment by JerryCasiano** [comment]
I've added this to a "Known Issues" list so closing this out.
