### ISSUE TITLE
Doubleclicking on a typeface gives [font-manager]-CRITICAL in a loop

### ISSUE THREAD

**Issue by spezialspezial** [FontManager/font-manager#248]
**Describe the bug**
Sorry, 

with the PPA version, v 0.8.7, started via terminal to get stdout, when doubleclicking a typeface I get 

(font-manager:262953): [font-manager]-CRITICAL **: 23:54:22.508: font_manager_string_set_get: assertion 'self != NULL' failed

in a tight loop, a hundred times (maybe the numer of typefaces?), blocking the app while in the loop.

**To Reproduce**
1. Go to Compare mode, wide layout
2. Expand a type family
3. Doubleclick a typeface name
4. If you have stdout on display you should see the error message

**System Information**
Ubuntu 20.04, PPA version 0.8.7

**Comment by JerryCasiano** [comment]
Thanks for reporting this.

This is fixed in the latest commit and should be available in the PPA version within a day.
