### ISSUE TITLE
[Feature request] Add "Preview" mode to Manage Google-Fonts mode

### ISSUE THREAD

**Issue by spezialspezial** [FontManager/font-manager#250]
Not a huge issue but "Preview" mode (editable sample text, all characters, justification) is missing when in Manage -> G mode. Only Waterfall and Lorem Ipsum is availiable. Not sure if this is for technical reasons. Just in case it's easy to add I wanted to mention it's missed as it's my favorite mode.

**Comment by JerryCasiano** [comment]
It is for technical reasons actually.

We would need to involve actual JavaScript for something like that to work. 

At that point, we would probably be better off dumping the pure GTK widget and just using a WebView for previews everywhere in the application.

Which may or may not be a bad idea actually.

I don't know... I considered doing it for consistency but didn't really want to go that far with it at the time.

I think I'll leave this open for now and revisit it later. May be a while though. Possibly something to seriously consider in a GTK 4 or 5 port.

Thanks for your interest.

**Comment by spezialspezial** [comment]
No problem, could have been a simple oversight.

**Comment by JerryCasiano** [comment]
I'm closing this out now as this is already done in the wip branch and will be in the next release.

Thanks for the push.
