### ISSUE TITLE
Website redirects to GitHub

### ISSUE THREAD

**Issue by milotype** [FontManager/font-manager#259]
**Describe the bug**
The [Font Manager website](fontmanager.github.io/) redirects automatically to the [GitHub page](https://github.com/FontManager/font-manager).

**Expected behavior**
Website shouldn't redirect automatically to the GitHub page.

**Screenshots**
![website-redirect](https://user-images.githubusercontent.com/43657314/149134212-3d5f7977-2cdf-49e9-a419-85ac6061fc74.png)

**Comment by JerryCasiano** [comment]
> Website shouldn't redirect automatically to the GitHub page.

Why is that?


More importantly though, are you volunteering to update and maintain a separate site going forward?

Because if you're not then the redirect will remain in place.

**Comment by milotype** [comment]
@JerryCasiano OK, I just thought it was a mistake.
