### ISSUE TITLE
Disable/enable multiple fonts

### ISSUE THREAD

**Issue by srackham** [FontManager/font-manager#261]
_Font Manager_ allows you to disable fonts one at a time but there does not seem to be a way to disable a selection of fonts.

My Linux desktop has almost 300 fonts and I want to whittle it down to a dozen or so -- clicking each one will be tedious.

It would be nice to use _Shift+click_, _Ctrl+click_ and _Ctrl+A_ to create a selection and then enable/disable with a single click.

I considered editing `~/.config/fontconfig/fonts.conf` (see https://askubuntu.com/a/1140105/318486) but that's also pretty daunting.

**P.S.** You can use _Shift+click_, _Ctrl+click_ and _Ctrl+A_ to multi-select font list items, but when you click the check-box only the clicked item gets disabled.

The screenshot in this 2009 post suggests that a multi-select disable once existed (https://forums.linuxmint.com/viewtopic.php?t=259109)

**Comment by JerryCasiano** [comment]
The last commit added a right click menu which allows you to enable / disable selected items.

**Comment by JerryCasiano** [comment]
By the way, I typically use collections for this purpose.

Just another option.

**Comment by srackham** [comment]
Wow, that was fast work! I'll give it a go when the update drops.

Thank you
