### ISSUE TITLE
Doesn't change system fonts

### ISSUE THREAD

**Issue by taep96** [FontManager/font-manager#263]
**Describe the bug**
When trying to change system fonts in Preferences changes persist between app restarts but don't actually work

**To Reproduce**
1. Go to Preferences
2. Click on Desktop
3. Change Interface/Document/Monospace font

**Expected behavior**
Different fonts than default ones

**Screenshots**

**System Information**
 - OS: Arch
 - Desktop Environment: dwm
 - Font Manager version: 0.8.7

**Comment by PF4Public** [comment]
> 4\. See error

And the error is…?

**Comment by taep96** [comment]
> > 4. See error
> 
> And the error is…?

No error, forgot to remove from issue template

**Comment by JerryCasiano** [comment]
Is DWM compatible with GNOME settings regarding fonts?

I wouldn't have thought that to be the case.

**Comment by taep96** [comment]
On GNOME to configure fonts I have used gnome-tweaks. Settings used in tweaks only worked in GNOME and not on any other DE/WM.

On Arch fonts are configured using fontconfig. Configurations files can be found in `/etc/fonts/conf.d/`

**Comment by JerryCasiano** [comment]
> On GNOME to configure fonts I have used gnome-tweaks. Settings used in tweaks only worked in GNOME and not on any other DE/WM.

Correct 

That's exactly why our README clearly states that desktop font settings are only available on GNOME or environments compatible with GNOME.

> On Arch fonts are configured using fontconfig. Configurations files can be found in `/etc/fonts/conf.d/`

There's plenty of Fontconfig specific settings exposed within the preferences pane. However, Fontconfig does not have the concept of default document font or default interface fonts or default whatever else, that's desktop and application specific. Fontconfig has the concept of aliases and uses three default aliases sans, serif and monospace, that's it.

And you can already easily set an alias using the relevant preference pane.

I'm closing this for now.

Feel free to continue the discussion here if you have questions or whatever.

Thanks.
