### ISSUE TITLE
0.8.8 Release

### ISSUE THREAD

**Issue by JerryCasiano** [FontManager/font-manager#265]
I plan on tagging a new release sometime soon, probably a week or two at most.

Not too many changes since last release but issues such as #240 will probably start to affect users if not done.

If there's anything that needs to go in or any issues with the latest revision please comment here.

Thanks.

**Comment by PF4Public** [comment]
Have you added any new user-visible strings since 7af8c463da076afecbc9e1b4ca9ee42c0cf4d627? If that's true, *.pot file and translations need to be refreshed.

**Comment by JerryCasiano** [comment]
Yup.

A few new strings did find their way into the code for #261 so those probably haven't been translated at this point.

**Comment by PF4Public** [comment]
Oh, indeed. I could refresh them and add new RU/DE strings. But don't expect it being fast as I'm heavily occupied at work.

**Comment by JerryCasiano** [comment]
No biggie. Take your time. You just reminded me I should probably update the vendor list also since it's been awhile.

**Comment by PF4Public** [comment]
> You just reminded me

;)

PS: I have a suspicion about (un-)translatability of the following:
https://github.com/FontManager/font-manager/blob/85dd400c3cced784a86e9218ca896562e3d5f2af/src/font-manager/FontList.vala#L413

Will it account for plural forms?

**Comment by JerryCasiano** [comment]
Sure doesn't look like it... does it? :-D

Oops, I'll fix it later today. Thanks for pointing it out!

**Comment by PF4Public** [comment]
I do understand your reasoning for it being used only in plural context. 

This is definitely true for English and its relatives, but does not hold in general. Slavic languages for example have at least 2 forms for plurals. I cannot find any wiki article for that atm, but for a quick reference, see:  [ru.po#L32-L33](https://github.com/FontManager/font-manager/blob/74cf626e0f9a49995a7ce9535bc6562324ff894d/po/ru.po#L32-L33) and [pl.po#L16-L17](https://github.com/FontManager/font-manager/blob/74cf626e0f9a49995a7ce9535bc6562324ff894d/po/pl.po#L16-L17). And it gets even more complicated in arabic: [ar.po#L15-L16](https://github.com/FontManager/font-manager/blob/74cf626e0f9a49995a7ce9535bc6562324ff894d/po/ar.po#L15-L16)

If you used the same assumption with any other strings, it would be great to fix them all.

**Comment by JerryCasiano** [comment]
Well it can never be singular, unless we have a bug. And there is no other matching string anywhere that I know of.

I'm happy, as you know, to reformat it or change it in any way that would make it easier to translate, but the thing is I'm not exactly sure of what changes actually need to be made to that string, if any.

Definitely open to suggestions.

**Comment by PF4Public** [comment]
Okay, lets try it the other way around.
| English | Russian |
| ------------- | ------------- |
| 1 item | 1 элемент |
| 2 item**s** | 2 элемент**а** |
| 5 item**s** | 5 элемент**ов** |
| 21 item**s** | 21 элемент |

I can put neither "элемент**а**" nor "элемент**ов**" as a translation. Plurals still need to be accounted for.

**Comment by JerryCasiano** [comment]
Yeah, that sounds like we need to feed a "fake" string to gettext then.

I'll push a commit with that change in a bit. If you can test that it works with your translation that would be great.

**Comment by PF4Public** [comment]
Unfortunately this didn't work :(
Compare https://github.com/FontManager/font-manager/blob/7fbc98442d0da9a4fcdb4046a738a344836acb6a/po/font-manager.pot#L792-L795
and https://github.com/FontManager/font-manager/blob/7fbc98442d0da9a4fcdb4046a738a344836acb6a/po/font-manager.pot#L684-L689

**Comment by JerryCasiano** [comment]
@PF4Public 

Thanks!

I think the last commit should work?

**Comment by PF4Public** [comment]
@JerryCasiano Now it looks as it should be:
![image](https://user-images.githubusercontent.com/10319700/152213295-3ce84123-a540-4ae9-96dc-3cd0612f8da5.png)

**Comment by JerryCasiano** [comment]
Sweet!

I'll probably tag a release over the weekend or early next week.

By the way, thanks for pointing out these issues and I appreciate your patience. I "get it" until the next time when I for whatever reason seem to completely forget that there are languages that handle plurals in different ways depending on context. :-D

**Comment by PF4Public** [comment]
> I for whatever reason seem to completely forget

I'm watching you ;)

Looking at it again it seems ugly to me to have plural at both places. We have discussed this here and are aware of singular not being used, but this is very misleading on its own for other people, seeing this string for the first time in Weblate for example. This might even lead to a false issue-report. Let's put proper singular and plural there and leave a note that singular is never used (at least not yet).

**Comment by JerryCasiano** [comment]
> I could do the PR. This actually holds me from adding those new 3 strings.

Sounds good to me.

**Comment by PF4Public** [comment]
All seems to be in place now :)

![image](https://user-images.githubusercontent.com/10319700/152873872-11b9dad2-b370-43d5-988e-4ce6509cdc90.png)
![image](https://user-images.githubusercontent.com/10319700/152874112-2bf281a9-4e1a-4261-95af-fb050caa8c7c.png)
