### ISSUE TITLE
Can't install from pacman

### ISSUE THREAD

**Issue by LukeFernandes** [FontManager/font-manager#270]
I get 'target not found: font-manager'.

If this has been removed from the official repositories, could you please update the readme?
I will get it from the AUR instead.

**Comment by JerryCasiano** [comment]
The Arch section of the README was last updated by @alerque who happens to be the maintainer and just recently moved the package to [Community].

https://archlinux.org/packages/community/x86_64/font-manager/ is still valid.

While the previous AUR link leads to a 404.

So... Are you sure it's been removed? 

In any case, I'm going to wait a little while before doing anything with the README.

**Comment by alerque** [comment]
@LukeFernandes It is still in the official repositories. It sounds like your system might be out of date, and and your package database is old. As with **all** installations on Arch Linux partial upgrade situations (e.g. installing a freshly released package on a system that hasn't been updated) is not supported. First update your system, then font-manager will install just fine:

```console
# Freshen package database and sync all system packages with it
$ pacman -Syu

# Install font manager (which will be found in the current database)
$ pacman -S font-manager
```

**Comment by JerryCasiano** [comment]
@alerque 

Thanks for confirming this.

I assumed this was the case but haven't used Arch in quite a while so didn't want to give out bad info.
