### ISSUE TITLE
Broken UI in version 0.8.7-3

### ISSUE THREAD

**Issue by Pound-Hash** [FontManager/font-manager#276]
**Describe the bug**
The left-hand pane no longer appears correctly after latest update. I tried cleaning the respective `.cache` and `.config` folders.

**Screenshot**
![20220204_14h09m45s_grim](https://user-images.githubusercontent.com/51193876/152610307-04b789e1-01db-4f77-b58d-ae22124f06b7.jpeg)

**System Information**
 - OS: Arch Linux
 - Desktop Environment: Sway
 - Font Manager version [0.8.7-3] 
 - Font Manager installation method [Arch core repo]

**Comment by JerryCasiano** [comment]
You're going to need to provide a little more detail than that...

While you may consider it obvious, I'm sorry but I'm just not seeing it.

**Comment by Pound-Hash** [comment]
There used to be categories on the left, e.g., _All_, _System_, _User_, _Family Kind_, _Width_, etc. And then, on the right of that pane, there would be a list of fonts. But now those categories are gone. And the fonts listed are not correct. Sometimes when I open the app, no fonts appear. Sometimes they all appear. And in the case of the attached screenshot, only two are appearing (those two should belong to the _user_ category, which is gone).

**Comment by Pound-Hash** [comment]
The only information on the left pane in the screenshot is of _supported orthographies_. Is that intended? Maybe I'm mistaken.

**Comment by JerryCasiano** [comment]
You have the "Characters" tab selected in the preview area, so yes that is intended behavior. Whether it's the best UX decision or not is certainly up for discussion.

Select any of the other tabs and you should see the normal sidebar.

**Comment by Pound-Hash** [comment]
Oomph, okay, thanks.

**Comment by JerryCasiano** [comment]
Your welcome.

The interface is... 

Well, experimental, for better or for worse. It's not always intuitive at first but hopefully once you know what to expect it makes some sort of sense to you.

If you stumble into any other issues please feel free to ask here, notifications come through even on closed issues.

**Comment by PF4Public** [comment]
Indeed the UI in that part is somewhat confusing, but the sliding animation helps a tiny bit.

**Comment by JerryCasiano** [comment]
@PF4Public 

It really is.

I just haven't come up with a better solution that doesn't make the interface even more cluttered. 

Definitely need to revisit these types of things when we port to GTK 4. Which I've started playing with again now that a compatible WebKit is getting closer.
