### ISSUE TITLE
Show full info in the `Properities` tab by default

### ISSUE THREAD

**Issue by c02y** [FontManager/font-manager#292]
**Is your feature request related to a problem? Please describe.**

When I open font-manager for a font such as `font-manager fontname.ttf`, it is started with `Properties` tab, most of time I need to check all the info such as `Family`, `Version` on the left pane under `Properties` tab, but every time I open font-manager, font-manager shows only a small part of the left pane, check screenshot. I need to manually resize the left pane using mouse to see the full info.

![image](https://user-images.githubusercontent.com/2135996/165001683-faef87b7-f0a6-4bae-a97c-da398af6f576.png)

**Describe the solution you'd like**

Auto display full info one the left pane by default when I open font-manager for a font file
![image](https://user-images.githubusercontent.com/2135996/165001699-3191d6b8-7a13-4103-b219-b07844544155.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Moilleadoir** [comment]
This kind of thing plagues Linux programs.

**Comment by JerryCasiano** [comment]
@Moilleadoir 

If you don't have anything helpful to add, I'd appreciate if you take your opinions elsewhere, plenty of other places on the web to shitpost were you'll get more attention.

@c02y 

Not sure when the next release will be. Might be a while.

That said, it should be a pretty easy fix, I'll make sure it gets done for the next release. 

Thanks for reporting it. 

By the way, in case you didn't realize it, you can adjust the pane position, unfortunately it won't get saved so still annoying.
