### ISSUE TITLE
ppa is not updated for ubuntu 22.04

### ISSUE THREAD

**Issue by redwan-hossain** [FontManager/font-manager#293]
**Describe the bug**
E: The repository 'https://ppa.launchpadcontent.net/font-manager/staging/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**To Reproduce**
add the PPA and do an apt update

**Expected behavior**

**System Information**
 - OS: Ubuntu 22.04
 - Desktop Environment Budgie
 - Font Manager version [e.g. 0.8.4] 
 - Font Manager installation method- PPA

**Comment by JerryCasiano** [comment]
Should be good now
