### ISSUE TITLE
[Feature Request] Add an option to sort/alphabetize user font collections

### ISSUE THREAD

**Issue by ghost** [FontManager/font-manager#297]
**Is your feature request related to a problem? Please describe.**
It's challenging to sort and re-arrange my font collections in the "Collections" pane. I want them to be in a logical order, such as alphabetical order.

**Describe the solution you'd like**
I would like there to be something like a button that will sort my collections in alphabetical order.

**Describe alternatives you've considered**
I am currently just manually editing the `index` numbers in the `Collections.json` file (lol). But a more practical alternative could be to add another section to the "Settings" window with settings for the user's "Collections" and to give an option to automatically alphabetize the list of collections.

I'd also like to add that this program is amazing! I find it indispensable for keeping track of my fonts and organizing them.

**Comment by JerryCasiano** [comment]
Why are you manually editing a text file rather than dragging and dropping collections to where you want them?

**Comment by Morellet** [comment]
> Why are you manually editing a text file rather than dragging and dropping collections to where you want them?

Because when I try to drag and drop my collections to arrange them, sometimes I end up nesting one collection within another and then I can't seem to get it back to the "top level." Also, I'd like to just keep my collections arranged alphabetically and would rather not have to do it manually at all, whether by drag and dropping or editing a text file.

**Comment by JerryCasiano** [comment]
Fair enough.

I'll keep this in mind while porting to GTK 4.

The port itself is nowhere near ready though, so unfortunately it will more than likely be a while before you see this implemented. 

Thanks for the suggestion.

**Comment by Morellet** [comment]
Thanks so much! I'm excited to see the GTK 4 port!

**Comment by JerryCasiano** [comment]
There's a test branch [here](https://github.com/FontManager/font-manager/tree/wip-gtk4) where you can see some of the progress. It's slow going, GTK 4 still has some rough edges unfortunately.

**Comment by JerryCasiano** [comment]
I'm closing this out as this is now implemented in the [work in progress branch](https://github.com/FontManager/font-manager/tree/wip-gtk4) and will be part of the next release which is only a couple months away.

Thanks for suggesting this.
