### ISSUE TITLE
Buttons option for dialogs - header or not

### ISSUE THREAD

**Issue by OldGuit** [FontManager/font-manager#299]
The dialogs have the action buttons in the header whereas in the previous version I used they were at the bottom.
I am running Mint 21 Xfce. Where other applications placed the action buttons in the dialog header I have opted to move the buttons back to the bottom using Xfce's Settings Editor - adding Gtk/DialogsUseHeader to xsettings and making it FALSE. However, Font Manager (0.8.8) still places the action buttons in the header.
Is there an option somewhere to place the action buttons at the bottom of dialogs?
Or is this a 'bug' in that Font Manager is not adhering to the Gtk settings conventions?

**Comment by JerryCasiano** [comment]
Disable  Settings > Interface > Client Side Decorations  and restart the application.

It's all or nothing. There is no option to have HeaderBar used for main window and not for dialogs.
