### ISSUE TITLE
I'd like an option to install fonts without changing filenames

### ISSUE THREAD

**Issue by DanielMGessel** [FontManager/font-manager#300]
**Is your feature request related to a problem? Please describe.**
Renaming font files, specifically replacing hyphens with underscores, lead to frustrating inconsistencies between two systems despite installing the same distro on both (one upgraded a few times, the other brand new). My Emacs config worked fine on my old laptop, but took some extra wrangling to debug, then delete and reinstall fonts manually. (I follow the Lisp convention of using hyphens to separate words everywhere I can.)

Despite preferring hyphens to underscores, I am totally on board with eliminating spaces in filenames. For this, you have my undying support!

Seriously, I admit I may be ignorant of a good reason for the renaming. And, despite not having heard of Vala before an hour ago, I could probably tweak and build my own version if it's just a matter of convention (I do love to flaunt conventions).

**Describe the solution you'd like**
Have an option to not replace hyphens in filenames with underscores when installing fonts.

**Describe alternatives you've considered**
I deleted and reinstalled the fonts by hand without changing the filenames - but it was difficult to propagate the changes to Emacs; after a couple of repeated attempts it "just worked".

**Additional context**
The JuliaMono ttf font files have hyphens in them.

**Comment by JerryCasiano** [comment]
I considered making this fully configurable by the user, sounded like a good idea at first, however I decided against it for multiple reasons : 

1. It would likely add a lot complexity for very little benefit (most users wouldn't even use the feature)
2. We already allow users to easily add folders to the configuration

I think the entire point of installing fonts using the application is that you simply choose them in a file selector or drop them onto the list and you don't have to care about any of the details, I seriously considered simply using hashes for the filenames and a single directory level...

The fact that you can easily add any directory to the font configuration using the application kind of makes it pointless to implement such a feature. In this case you could just leave them wherever they are and simply add the directory as an always active source.

Appreciate the suggestion but I just don't think the pros outweigh the cons here.
