### ISSUE TITLE
Google Fonts button crashes session

### ISSUE THREAD

**Issue by stpnwf** [FontManager/font-manager#301]
**Describe the bug**
App crashes session when I click on the Google Fonts icon

**To Reproduce**
1. Open App
2. Click on 'Google Fonts' button
3. Screen goes black and I'm logged out
4. Log in screen shows up

**Expected behavior**
Button to work...

**System Information**
 - OS: Zorin OS 16.2 [Ubuntu 20.04 LTS based] on X11
 - Desktop Environment GNOME Shell 3.38.4
 - Font Manager version: 0.8.8 
 - Font Manager installation method: Flatpak

**Comment by JerryCasiano** [comment]
This is the first thing listed in #272 which is pinned to the top of the issues page ...
