### ISSUE TITLE
undefined symbol: sqlite3_column_origin_name

### ISSUE THREAD

**Issue by rutrum** [FontManager/font-manager#303]
**Describe the bug**
Crash on load.  I can see the UI for a brief moment before it closes.  Running from command line gives the error
```
font-manager: symbol lookup error: /usr/lib/x86_64-linux-gnu/font-manager/libfontmanager.so.0: undefined symbol: sqlite3_column_origin_name
```
My sqlite3 version is 3.39.3.

**To Reproduce**
1. Install on Ubuntu 20.04 using ppa
2. Open application

**Expected behavior**
Should not crash

**Screenshots**
Not applicable

**System Information**
 - OS: Ubuntu 20.04
 - Desktop Environment: Gnome
 - Font Manager version: 0.8.8
 - Font Manager installation method: PPA

**Comment by PF4Public** [comment]
This is more likely a packaging issue.

**Comment by JerryCasiano** [comment]
Yeah, that looks like a library mismatch...

20.04 is an LTS release and appears to be compiled against 3.31 on Launchpad which appears to be the latest version available for that release.

So the question is how and why is your system at 3.39?

**Comment by JerryCasiano** [comment]
Suspect this is user error, closing due to lack of response.
