### ISSUE TITLE
cannot drag fonts to collections

### ISSUE THREAD

**Issue by LuigiWriter** [FontManager/font-manager#309]
This is happening in new install of Ubuntu Studio on new hardware.
This seeming bug is common to both of the following versions:

- Ubuntu-jammy-universe (Ubuntu 22.04.1 LTS) - 0.8.8-1
- flathub (Flatpak) - stable 0.8.8

This drag and drop problem has not been encountered with other applications.
The two screenshots below were dragged and dropped from Dolphin into this report.

**Describe the bug**
I cannot drag fonts to collections I have created
Nor does there seem any alternate way of doing it. ie: copy and paste a link.

**To Reproduce**
1. Load Ubuntu Studio 22.04.1 LTS [1]
2. Click on [Application Launcher]
3. Scroll down to and click on [Utilities]
4. Click on [Font Manager]
5. In left pull down menu click [Browse]
6. In the collections section Click [-->] to open the collections list.
7. Click [+] in the bottom selections 
8. Add a name for the new collection and press [Enter]
9. In the Categories section above click on [All] 
10. Move mouse cursor over a font name.
11. Attempt to Click and drag the font name to the collection on the left.
12. Click on the Collection in which the font should be listed

**Actual behavior**
- Find that neither a copy of the family name or the individual font name moves with the cursor.
- Find that the collection remains empty.

[1] Note: I have not tested this in Ubuntu 22.04.1 LTS, Only on **Ubuntu Studio 22.04.1 LTS**.

**Expected behavior**
- Expect a copy of the font name to move with the cursor to the collection and disappear when dropped
- Expect to see the font listed within the collection.

**Screenshots**
![Cursor over font](https://user-images.githubusercontent.com/30986842/218586800-7b67e17f-0986-4d6c-81a4-95dd04b31989.png)

![Empty collection](https://user-images.githubusercontent.com/30986842/218587120-e7a73efe-68b2-4a2c-b265-ff7b50e27eb6.png)

**System Information**
Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-60-lowlatency (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 7900X 12-Core Processor
Memory: 31.1 GiB of RAM
Graphics Processor: llvmpipe**System Information**

**Font Manager versions tested**
- Ubuntu-jammy-universe (Ubuntu 22.04.1 LTS) - 0.8.8-1 [I assume PPA]
- flathub (Flatpak) - stable  0.8.8 
Both Font Manager installations were through the org.kde.discover application.

**Additional context**
As indicated above this is experience with new hardware, OS, and the applications provided within. With 32 GiB up from 4 GiB RAM old laptop's hard drive continuous whine with Ubuntu 18.04 is blessedly absent. I am a writer and fonts are an important part of what I do. Without Font Manager sifting through more than the seeming 1,000 or more fonts provided is dizzying at least for me. I want to help in anyway I can to be able create collections useful to that end. 
I will do my best to provide anything else needed.

**Comment by JerryCasiano** [comment]
The screenshots you provided show the application in "Browse" mode.

You are experiencing this issue in "Manage" mode, correct?

Browse mode doesn't allow actions that would be considered "management". If you were attempting these actions in browse mode pllease switch to manage mode by using the menu in the upper left corner or the Alt+1 shortcut and verify the issue is still present.
