### ISSUE TITLE
Font manager 0.8.8 fails to build with clang15

### ISSUE THREAD

**Issue by ehaupt** [FontManager/font-manager#310]
**Describe the bug**
FreeBSD recently imported llvm15 to the main branch. Font manager now fails to compile.

**To Reproduce**
Compile font manager 0.8.8 with llvm15.

**Expected behavior**
Expect it to compile without an error.

**System Information**
 - OS: FreeBSD 14.0-CURRENT, amd64 (not arch specific)
 - Desktop Environment not relevant for this compiler error
 - Font Manager version 0.8.8 

**Additional context**
Compiler error with clang15 [font-manager-0.8.8_2.log](https://github.com/FontManager/font-manager/files/10757147/font-manager-0.8.8_2.log)

**Comment by JerryCasiano** [comment]
Huh. Looks like it doesn't like the coffee generated by Vala.

Thanks for reporting, I'll see if I can workaround it over the weekend.

**Comment by JerryCasiano** [comment]
Can you please verify that the latest commit allows the build to succeed on FreeBSD? 

If you need a release tagged please let me know. Otherwise feel free to close if the latest commit is good to go.

Thanks.

**Comment by ehaupt** [comment]
> Can you please verify that the latest commit allows the build to succeed on FreeBSD?

Thank you, will do, I'll get back to you ASAP.

**Comment by ehaupt** [comment]
> Can you please verify that the latest commit allows the build to succeed on FreeBSD?

I confirm that the commit https://github.com/FontManager/font-manager/commit/b65f10af7996945d1cc3e1fcc0b157df701173f4 solves the issue.

> If you need a release tagged please let me know. Otherwise feel free to close if the latest commit is good to go.

If you could tag the commit with a bugfix or minor release that would definitely help with the packaging but if you'd like to wait I could work around it.

Thank you for that very fast response :100:

**Comment by JerryCasiano** [comment]
If you can workaround it please do, I would rather not bump the version until absolutely necessary at this point.

Thanks again for reporting this and verifying the fix.
