### ISSUE TITLE
Latest Version force closes Play Store

### ISSUE THREAD

**Issue by schmeggy929** [FontManager/font-manager#311]
Latest version 5.7.6, when you open Play store/Settings/Manage apps & device the app force closes. Uninstall Font manager and issue is gone. Phone is Google Pixel 7 Pro with latest Android 13 build version TQ1A.230205.001.D2

**Comment by JerryCasiano** [comment]
You have the wrong issue tracker.

That is not the latest version and this isn't an Android application...
