### ISSUE TITLE
Supported Orthography settings are not completely saved

### ISSUE THREAD

**Issue by bdeshi** [FontManager/font-manager#314]
**Describe the bug**
in the supported orthography filter category, selected orthographies are saved between restarts, but the minimum coverage resets to 90 after font-manager is re-opened.

**To Reproduce**
1. Go to managed mode, click on categories, then supported orthographies.
3. click the edit button at bottom right of sidebar.
4. Select one or more orthographies, and set minimum coverage to anything that's not 90.
5. close and re-open font-manager.
6. click the edit button for supported orthographies again.
7. previously selected orthographies are still selected, but minimum coverage gets reset to 90.

**Expected behavior**
custom values for the minimum coverage box should be remembered, similar to selected orthography list items.

**Screenshots**
![image](https://user-images.githubusercontent.com/3525376/226189086-5ac976a6-032f-43de-927c-cd497b2ea136.png)

**System Information**
 - OS: Arch linux, x64, linux kernel v6.2.7
 - Desktop Environment: none.
 - Font Manager version: 0.8.8
 - Font Manager installation method: archlinux official package repository

**Comment by JerryCasiano** [comment]
Thanks for reporting.
