### ISSUE TITLE
[Feature suggestion] Filter fonts (beyond filtering typefaces)

### ISSUE THREAD

**Issue by noyannus** [FontManager/font-manager#316]
The filtering could be extended to finer granularity and work on individual fonts, beyond filtering typefaces (font families). See below; it shows a test collection with the DejaVu families.

![Screenshot_2023-03-22_08:30:05](https://user-images.githubusercontent.com/6339921/226835873-17021f6c-8fce-4b8d-8255-2516e2472507.png)

![Screenshot_2023-03-22_08:30:56](https://user-images.githubusercontent.com/6339921/226835903-1da871ff-4afd-41fd-9aea-aaa6a1c62f59.png)

![Screenshot_2023-03-22_08:31:23](https://user-images.githubusercontent.com/6339921/226835926-2f6683db-b996-47eb-9a75-034890cd4ad3.png)

![Screenshot_2023-03-22_08:31:39](https://user-images.githubusercontent.com/6339921/226835937-26e90c49-1851-45ba-8995-98c835461f0d.png)

![Screenshot_2023-03-22_08:31:55](https://user-images.githubusercontent.com/6339921/226835949-b2678193-92a7-42e9-9b73-09122cf6fe75.png)

![Screenshot_2023-03-22_08:32:08](https://user-images.githubusercontent.com/6339921/226835961-ccb2f9f4-cac3-4fb4-bd66-9f0e0ba66c00.png)

**Comment by JerryCasiano** [comment]
Unfortunately it looks like backporting is not going to be quick and easy.

The GTK 4 port is not perfect in this regard either but it does seem to already work better in this regard.

![bold_search](https://user-images.githubusercontent.com/11490124/227050005-f716b414-7b4d-4722-b5ee-de9839b0d43e.png)
![oblique_search](https://user-images.githubusercontent.com/11490124/227050014-c0a62601-965c-4fb0-a865-fa115fb02e8e.png)
![semi_search](https://user-images.githubusercontent.com/11490124/227050026-93b37d15-cdc7-47b2-951b-c0d9bb0228e5.png)

Sorry, but it'll probably be a while on this. Aside from serious bugs or quick and easy fixes the focus of development is now squarely on the GTK 4 port, so I'm punting this till that releases.

We can keep this open as a motivator.

**Comment by JerryCasiano** [comment]
> The search field could be auto expanding with pane width to be very broad, or at least have a much larger fixed width. You'd get a fair gain in functionality for a small aesthetic cost.

Well, aesthetics are important, not as important as function of course but still an important consideration. 

> To demonstrate with an example, users might want to see at a glance whether they are searching for
> DejaVuSansMono Nerd Font Mono Bold, or for
> DejaVuSansMono Nerd Font Mono Bold Oblique,
> but now see only truncated bits from DejaVuSansM to old Oblique. And there may exist even longer font [family] names or character widths.

I'm not sure searching for that long and detailed of a string is a very common scenario. At least not common enough to justify making the search entry larger.

In any case, the GTK 4 port will allow for matching chunks so that should prevent such overflow without making the search field huge at all times and still allow you to drill down pretty far. ;-)

![less_typing](https://user-images.githubusercontent.com/11490124/227419621-8707a3f8-6b7e-461d-8a3b-5a832460170a.png)

![much_less_typing](https://user-images.githubusercontent.com/11490124/227420088-bddaae08-8032-4258-a9b1-aa45895b6d53.png)

**Comment by noyannus** [comment]
> Well, aesthetics are important, not as important as function of course but still an important consideration.

Not arguing with that. Decades with macs as main production machines (I'm migrating right now) made me appreciate a well thought out design and user experience very much. But also, that sometimes ease of function > good looks. I'm very happy to see both in the upcoming versions. 

> I'm not sure searching for that long and detailed of a string is a very common scenario. At least not common enough to justify making the search entry larger.

> In any case, the GTK 4 port will allow for matching chunks so that should prevent such overflow without making the search field huge at all times and still allow you to drill down pretty far. ;-)

The best of both worlds. Thanks for the time you took to explain!
