### ISSUE TITLE
Please consider changing your application identifier

### ISSUE THREAD

**Issue by brittyazel** [FontManager/font-manager#319]
Hello Font Manager Team,

Thank you for writing this application and adding to the ecosystem of apps available on Flathub for GNOME!

I'm writing to ask if you would consider renaming your application identifier so as not to contain org.gnome prefix both within the application itself and for its listing on Flathub.

The GNOME Foundation appointed the GNOME Release Committee in charge of setting the guidelines to define which applications were allowed to use the GNOME trademark. To avoid confusion as to which software is or isn't produced or endorsed by the GNOME project, only applications approved by the release committee (typically only core applications or developer tools) should use the org.gnome prefix for their application, according to the software policy: https://wiki.gnome.org/Foundation/SoftwarePolicy

Would it be possible to adjust your app identifier so as to follow this policy?

Please let me know if you have any questions regarding this and apologies that this wasn't picked up earlier.

Cheers,
Britt Yazel, PhD
The GNOME Foundation

**Comment by JerryCasiano** [comment]
Discussed in #286 

Will happen when the GTK 4 version releases but unfortunately not before then.

**Comment by brittyazel** [comment]
Thanks, that seems reasonable. I appreciate you adding this to your milestones!

Can you see too it that this change propagates to the Flathub listing as well? I'm not sure if the packager of the [Flathub manifest ](https://github.com/flathub/org.gnome.FontManager )is involved upstream with you at all. If not, I can open a ticket there to place it on their radar that this change is coming down the pipe

**Comment by Eonfge** [comment]
@brittyazel I'm here! I'm tracking the releases and when the GTK 4 version comes out, I'll gladly change the Flathub App Id. I've done so before with a few projects who changed their Id so I know the drill.

**Comment by Eonfge** [comment]
Got another idea, @JerryCasiano, have you considered GNOME Circle? It's a group of high quality, GNOME related applications. Those apps are not officially GNOME, but they do conform to the GNOME HIG and such.

https://circle.gnome.org/

**Comment by JerryCasiano** [comment]
@Eonfge 

I have not, for various reasons. 

We don't use libhandy and don't plan on adopting the Adwaita library.

We're also not the most accessible application, but focusing on that doesn't really make sense for us anyway.

**Comment by Eonfge** [comment]
Quick heads up, I've not forgotten about this issue and when we have the next major release, I'll gladly migrate the Flathub project.
