### ISSUE TITLE
Simplify the character list creation

### ISSUE THREAD

**Issue by GrimPixel** [FontManager/font-manager#323]
**Is your feature request related to a problem? Please describe.**
To add a character list, one has to add it at least to
* 'build-aux/orthographies/'
* 'build-aux/orthographies/class2struct.cpp'
* 'build-aux/orthographies/fontaine'
* 'build-aux/orthographies/fontaine/orthographies.h'
* 'lib/common/font-manager-orthography.h'
* 'lib/orghographies/'

**Describe the solution you'd like**
Use one list only.

**Comment by JerryCasiano** [comment]
No. You don't have to edit all that.

Ignore anything in build-aux. I'll remove all that stuff and update any README files that need updating in a future commit. Fontaine does not appear to be active so contributing back is not something to worry about anymore.

Simply edit whichever orthographies you want to edit in place.

For the the GTK 4 branch that means lib/orthographies

**Comment by GrimPixel** [comment]
I noticed that the third value of an orthography file is called a “key”. Is there any use of it?

**Comment by JerryCasiano** [comment]
The key is important, it is a character that MUST be present to support a particular orthography. If it's not we don't do any further processing the file simply cannot support that orthography.

**Comment by GrimPixel** [comment]
I am curious about what it does, instead of “it is important”.

**Comment by JerryCasiano** [comment]
I'm not sure how to explain it any clearer.

What exactly are you asking?

We are simply checking for codepoints present in the file when we decide whether it supports an orthography or not, if it doesn't contain the "key" codepoint we don't check any further. That's it, that's all there is to it.
