### ISSUE TITLE
Use characters instead of UTF values

### ISSUE THREAD

**Issue by GrimPixel** [FontManager/font-manager#325]
**Is your feature request related to a problem? Please describe.**
Every time I have to check the character's value and copy-paste.

**Describe the solution you'd like**
Use characters instead of values.

**Comment by JerryCasiano** [comment]
No can do. 

Technical issue.

**Comment by GrimPixel** [comment]
If even you don't like to explain, I have no intention to explore.

**Comment by GrimPixel** [comment]
You know, that's me. When a question is answered like the second comment, even once, there is no need to consider continuing the coorperation.
