### ISSUE TITLE
Font Manager correctly opens some otf files individually, but shows them as ttf when using the database

### ISSUE THREAD

**Issue by Windsurfer01** [FontManager/font-manager#326]
**Describe the bug**
I am developing a font in Fontforge. When right-clicking and opening an individual OpenType file in FontManager it is always identified correctly, and the waterfall display works. However. when opening FontManager and browsing the files, many OpenType files show as TrueType and the character and waterfall displays do
[u3a Sans for FontManager.zip](https://github.com/FontManager/font-manager/files/11654680/u3a.Sans.for.FontManager.zip)
 not work.

**To Reproduce**
Right-click on each of the attached files, and they should show as OpenType.
Browsing to them within FontManager and selecting them may show them as TrueType.

**Expected behavior**
They should always show as OpenType, and the character and waterfall displays should work.

**Screenshots**

**System Information**
FontManager 0.8.8
System:
  Kernel: 5.15.0-73-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.8
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX B450-F GAMING v: Rev 1.xx serial: <filter>
    UEFI: American Megatrends v: 3103 date: 06/17/2020
CPU:
  Info: 8-core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP arch: Zen 2 rev: 0 cache:
    L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2550 high: 3600 min/max: 2200/3600 boost: enabled cores: 1: 2200 2: 3600
    3: 3600 4: 2200 5: 2200 6: 2200 7: 2200 8: 3600 9: 2200 10: 2200 11: 2200 12: 2200 13: 3600
    14: 2200 15: 2200 16: 2200 bogomips: 115199
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] vendor: Tul driver: amdgpu
    v: kernel pcie: speed: 16 GT/s lanes: 16 ports: active: DP-2,DP-3 empty: DP-1,HDMI-A-1
    bus-ID: 0b:00.0 chip-ID: 1002:731f
[u3a Sans for FontManager.zip](https://github.com/FontManager/font-manager/files/11654663/u3a.Sans.for.FontManager.zip)

  Display: server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1080 s-dpi: 96
  Monitor-1: DisplayPort-1 mapped: DP-2 pos: primary,left model: AOC 24G2W1G4 res: 1920x1080
    dpi: 93 diag: 604mm (23.8")
  Monitor-2: DisplayPort-2 mapped: DP-3 pos: right model: AOC 24G2W1G4 res: 1920x1080 dpi: 93
    diag: 604mm (23.8")
  OpenGL: renderer: AMD Radeon RX 5700 XT (navi10 LLVM 15.0.6 DRM 3.42 5.15.0-73-generic)
    v: 4.6 Mesa 22.2.5 direct render: Yes

**Additional context**
Changing the name of the font in Fontforge sometimes, but not always, corrects the problem.

**Comment by JerryCasiano** [comment]
Thanks for the detailed report and attachment.

Been on holiday for a bit. Will look into it. Soon hopefully.

**Comment by Windsurfer01** [comment]
I just discovered two things:
1) When I copied all of the .otf files to another PC, all but one opened and displayed the characters correctly in FontManager. The same files also opened correctly in LibreOffice, and displayed in the Font selection dropdown.
2) When using the Nemo extension in LinuxMint the FontManager pop-up displays the characters correctly in the character view.

**Comment by JerryCasiano** [comment]
I couldn't duplicate this with the GTK 4 version so hopefully it is fixed for you. Feel free to reopen if not.
