### ISSUE TITLE
Flatpak is using a dead GNOME runtime

### ISSUE THREAD

**Issue by kjcole** [FontManager/font-manager#327]
**Description**
Flatpak is using a dead org.gnomePlatform runtime

**To Reproduce**

`flatpak update` produces the error:

```
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. 
   Please ask your application developer to migrate to a supported platform.

```
**Expected behavior**
A quiet and orderly transition befitting a democracy. 😉 In other words, no error.

**System Information**
 - OS: **Pop! OS 22.04 ("Jammy")**
 - Desktop Environment: **GNOME**
 - Font Manager version: **0.8.8**
 - Font Manager installation method: **flatpak**

**Comment by JerryCasiano** [comment]
I actually don't handle the Flatpak packaging at all.

@Eonfge does the packaging for Flatpak.

Let's see if he needs us to do anything on our end, and what that entails, in order to use the updated runtime.

**Comment by Eonfge** [comment]
The issue is on hold, until Font-manager is updated to support the latest release of `libsoup-3.0` and `webkit2gtk`. GNOME 43 had a major version update for libsoup so I have two options: Bundle libsoup-2.4 or wait for Font Manager to get an update.

I choose to wait, although in hindsight it might be worth patching it right now

**Comment by JerryCasiano** [comment]
Hmm...

Might have to backport some changes then.

**Comment by Eonfge** [comment]
I have it working right now, by bundling webkit2gtk manually. It does make the download size 4x larger, but it's a small price to pay in this case.

https://github.com/flathub/org.gnome.FontManager/pull/18

I've checked it with GNOME 43, I'll test it with GNOME 44 next.

**Comment by Eonfge** [comment]
I'll be updating Font Manager with GNOME 44 right now, but if you could make an 0.8.9 release, with `ibsoup-3.0` and `webkit2gtk-4.1` then that would be great!

**Comment by JerryCasiano** [comment]
@Eonfge 

I'm sorry I completely missed this request.

I'll try to make this happen soon.

**Comment by JerryCasiano** [comment]
@Eonfge 

The latest commit bumped the versions of those dependencies.

Also, if you have any info on the other issue the Flatpak was having maybe we can sort it out - I just need to understand what changes need to happen to make it work for Flatpak.
