### ISSUE TITLE
My locale is zh_CN.UTF-8, font-manager lacks 4 cjk fonts

### ISSUE THREAD

**Issue by viruscamp** [FontManager/font-manager#330]
**Describe the bug**
My locale is zh_CN.UTF-8, font-manager show 239 fonts, lacks 4 cjk fonts.

`LC_ALL=C font-manager` shows 243 fonts, 
`LC_ALL=zh_CN.UTF-8 font-manager` shows 239 fonts. 

`LC_ALL=zh_CN.UTF-8 font-manager -l` shows all 243, the 4 lacks fonts are:
```
思源黑体 CN
思源宋体 CN
文泉驿微米黑
文泉驿等宽微米黑
....
```

`LC_ALL=C font-manager -l` shows all 243, the 4 lacks fonts are:
```
Source Han Sans CN
Source Han Serif CN
WenQuanYi Micro Hei
WenQuanYi Micro Hei Mono
...
```

**System Information**
 - OS: Arch
 - Desktop Environment [e.g. GNOME, XFCE, etc]
 - Font Manager version extra/font-manager 0.8.8-1 and aur/font-manager-git 0.8.8.r54.g7ba0a33e-1
 - Font Manager installation method [e.g. Distribution package, PPA, COPR, AUR, etc]
 -  Additional fonts pkgs:
    adobe-source-han-sans-cn-fonts
    wqy-microhei

**Comment by viruscamp** [comment]
![image](https://github.com/FontManager/font-manager/assets/5574216/12d47b93-9c05-4c89-a580-f133b6ed5cc4)
![image](https://github.com/FontManager/font-manager/assets/5574216/c5e15456-e1a5-409e-a4f5-a9f66b455136)

**Comment by viruscamp** [comment]
![image](https://github.com/FontManager/font-manager/assets/5574216/fc5e050d-d990-4941-91d6-9d8fc5b2f798)
![image](https://github.com/FontManager/font-manager/assets/5574216/5f95a27c-ccf0-4ffa-877f-eb7c16e60cd0)

**Comment by viruscamp** [comment]
I've found the cause:
The first run was not under zh_CN.UTF-8, font-manager created db file as `~/.cache/font-manager/Fonts.sqlite`, and saved the names below:
```
Source Han Sans CN
Source Han Serif CN
WenQuanYi Micro Hei
WenQuanYi Micro Hei Mono
```

After sometimes, I changed my lang to zh_CN.UTF-8, so I ran font-manager under zh_CN.UTF-8,

Let's look at `src/font-manager/filters/Category.vala`
```vala
public new async void update () {
    get_matching_families_and_fonts(db, families, descriptions, sql); // load from db, got Source Han Sans CN
    StringSet? available_families = get_default_application().available_families; // load from fontconfig, got 思源黑体 CN
    families.retain_all(available_families); // no Source Han Sans CN nor 思源黑体 CN
    return;
}
```

**Comment by JerryCasiano** [comment]
Sorry for the late response. Haven't been active for a while.

I appreciate you taking the time to not only find this bug but actually determine the cause.

A couple ways we could resolve this. Will keep this in mind for the next version.

Most likely we'll just do with the database what we do with the Google fonts cache which is drop it after a couple days but it might also make sense to drop it whenever environment values change. We'll see.

Thanks again.

**Comment by JerryCasiano** [comment]
@viruscamp 

We now drop the Fonts table everytime we update the database.

I think this should prevent the issue you encountered.

Feel free to reopen this if it doesn't. 

Thanks.

**Comment by JerryCasiano** [comment]
While dropping the font table did seem to resolve the missing fonts situation it failed to address outdated orthographies which meant invalid sample strings on locale changes. 

We now track the locale when the database was last updated and rebuild the database anytime it changes.
