### ISSUE TITLE
Allow users to preview in 2 or more selected languages

### ISSUE THREAD

**Issue by MarjaE2** [FontManager/font-manager#331]
**Is your feature request related to a problem? Please describe.**
If I preview the fonts, it shows whether the font supports the Roman alphabet, or certain versions of it. It doesn't show whether it supports the Roman alphabet and other ones.

**Describe the solution you'd like**
Either 1. a longer preview including multiple alphabets, or 2. an option to customize the preview to decide what alphabets to choose.

**Describe alternatives you've considered**
I tried manually editing the preview, switching the input method and typing in another alphabet, but everything was stuck in the Roman alphabet.

**Additional context**
I am not familiar with Linux language and input method support, yet.

**Comment by MarjaE2** [comment]
P.S. If I view the character list, Font Manager shows the supported orthographies, but hides the categories, so I can't use the supported orthgraphies to sort into categories. Otherwise that might be easier.

**Comment by JerryCasiano** [comment]
Hmm. Not sure how to resolve this. Will look into it for the next version.

**Comment by MarjaE2** [comment]
I'm not seeing a language filter.

**Comment by MarjaE2** [comment]
If you mean opening the Google Fonts section, and "Supported Orthographies," if I expand the window, I can see Arabic, Bengali, 3 options for Chinese, and no more. I can't page down, and can't scroll down because separately-scrolling columns trigger my migraines.

**Comment by JerryCasiano** [comment]
No. I mean the supported orthographies filler in the normal categories section. It's the last one.

Once selected the edit button at the bottom should become active and allow you to modify the filter.

**Comment by MarjaE2** [comment]
Ah, okay! I hadn't figured out how to use that section.

**Comment by JerryCasiano** [comment]
I'm closing this as I think the last suggestion may have resolved it.

If not feel free to open and let me know why that solution is lacking.

Thanks
