### ISSUE TITLE
Allow to remove Ortography filter by clicking active filter

### ISSUE THREAD

**Issue by keunes** [FontManager/font-manager#332]
**Is your feature request related to a problem? Please describe.**
The Ortography filter is mutually exclusive, i.e. one filter can be selected at the time. Clicking another item switches the filter, clicking the currently active filter doesn't do anything. The 'Clear selected filter' is displayed at the bottom, and not very visible. So it took me a while to remove a currently active filter.

**Describe the solution you'd like**
When clicking on an active filter, disable that filter.

**Describe alternatives you've considered**
Move the 'clear selected filter' button to the top, as that's where these type of 'clear filter' buttons often are. But this might throw off existing users and makes the button a bit too prominent.

**Additional context**
n/a

**Comment by JerryCasiano** [comment]
I like this suggestion. Not sure if there's a technical reason why we don't this but I'll keep this in mind for the next version.

Thanks!

**Comment by JerryCasiano** [comment]
So trying to enable I remembered that the current situation is a work around to the fact that GtkListView does not send "duplicate" selections.

I'll leave this open for now,  there's probably some way to make this happen. But it is low on the priority list.

**Comment by JerryCasiano** [comment]
You'll have to double click the selected row to deselect it now. 

Couldn't get it working on a single click.
