### ISSUE TITLE
Font preview display issue

### ISSUE THREAD

**Issue by tempo660** [FontManager/font-manager#333]
I installed one new font for fun, but now all of my fonts are not displaying correctly in Font Manager. The fonts are all functional, it's just a display issue within Font Manager. Any ideas on what caused this and how to repair?
![font-manager-broken.png](https://github.com/FontManager/font-manager/assets/117519973/6ba39e94-fdd7-489b-aa38-d3978db90776)

**Comment by JerryCasiano** [comment]
Hopefully by now you've sorted this out.

If not, the only suggestion I can give you is to uninstall the file that caused the issue.

If you can attach the offending file here we might be able to find out why.
