### ISSUE TITLE
Minimum font size

### ISSUE THREAD

**Issue by haarp** [FontManager/font-manager#334]
Hey. Testing this program and so far it's a pretty neat tool. Thanks for writing it! I'm currently seeing if I can write/adapt a Gentoo ebuild for it.

I'd like to request the minimum font size that can be selected to go lower than 6pt. Especially on high-DPI screens, 5pt or even 4pt can still be legible.

Thanks!

**Comment by PF4Public** [comment]
> I'm currently seeing if I can write/adapt a Gentoo ebuild for it.

https://github.com/FontManager/font-manager#:~:text=Gentoo,pf4public%20Gentoo%20overlay

;)

**Comment by JerryCasiano** [comment]
Closing this out since there has been no response and I tend to agree with @PF4Public that anything under 6 is likely not very useful.

We can revisit in the future if someone manages to make a reasonable case for it.
