### ISSUE TITLE
Fonts with an apostrophe in the Name {the embedded name} cannot be disabled

### ISSUE THREAD

**Issue by frakier** [FontManager/font-manager#339]
**Describe the bug**
Had some fonts that would not turn off so I made a list. The common denominator was the apostrophe in the embedded name.
`baily's car, 
dirty baker's dozen, 
let's eat, 
oliver's barney, 
should've know, 
you're gone`

**To Reproduce**
Enable the fonts.
Try to disable the font.
System stalls for a second or two and the font is still on.

**Expected behavior**
Disabling a font should disable a font.

**Screenshots**
n/a

**System Information**
 - OS: Release Linux Mint 21.2 Victoria 64-bit; Kernel Linux 5.15.0-86-generic x86_64
 - Desktop Environment: MATE 1.26.0
 - Font Manager version: 0.8.8
   - IMPORTANT : Do not file issues for extremely outdated versions of the application.
                 Verify the issue can be duplicated with the latest release.
                 If you are running a "Long Term Support" version please open an issue at your distributions bug tracker instead
 - Font Manager installation method: Software Manager System Package
**Additional context**
I don't know much about making fonts past using BirdFont and Similar apps, so maybe the font creator should not be using the apostrophe at all so maybe not a bug on your software so much as abused standards in naming the font but it is a bit of an issue.

**Comment by JerryCasiano** [comment]
Thank you for reporting this. 

Will look into it. May take a bit though.

**Comment by JerryCasiano** [comment]
This seems to be fixed in the latest commit but for now you'll need to use the PPA or build from source to see the changes.
