### ISSUE TITLE
Switch from webkitgtk 4.0 to 4.1

### ISSUE THREAD

**Issue by jbicha** [FontManager/font-manager#343]
**Describe the bug**

Distros currently need to build webkitgtk 3 times: once for GTK4 (6.0 API), once for GTK3 + libsoup3 (4.1 API ) and once for GTK3 + libsoup2.4 (4.0 API). Distros would like to drop the GTK3 + libsoup 2.4 build. The 4.0 and 4.1 APIs are the same except for the switch from libsoup 2.4 to libsoup 3.

**Expected behavior**
Please allow building font-manager with webkitgtk 4.1. I understand that it is already possible to build without the Google Fonts feature to build without webkitgtk 4.0.

I noticed that the wip-gtk4 branch has a commit f1d2454f5d0331f85bb157e0867d2955625269f4 to switch to the 6.0 API (which also uses libsoup3). Is it possible to port the libsoup3 work back to the stable branch of font-manager?

**Comment by JerryCasiano** [comment]
Sorry for the delayed response.

I'll try to have a look over the weekend and see if we can make that happen.
