### ISSUE TITLE
[Feature request] Clicking a font in Browse would jump on that in in Manage

### ISSUE THREAD

**Issue by grinapo** [FontManager/font-manager#347]
**Is your feature request related to a problem? Please describe.**
Browse mode lists the fonts but it's not possible to do anything with them, I kind of expected clicking on them may result … anything.
Immediately I wanted to disable/enable fonts, as the most obvious functionality. 
But generally it seems just logical that I can examine the browed font characters, license, etc. by selecting it in the Manage mode.

**Describe the solution you'd like**
Since manage mode lists fonts but doesn't show a visual image I have to either go Browse, find the font, go to Select, search for the same I have memorized and manage it; or I have to click on fonts in Select and see how they look like.

**Comment by JerryCasiano** [comment]
Browse mode is likely going away in the next version. 

I don't think it's all that useful and several users seem confused by it anyway.

I'm closing this out as there's not going to be any work on this.

It's possible something similar will take its place but it's unlikely to be a separate mode as it is in the current version, it's likely to simply be a different "view" of the font list going forward.

**Comment by grinapo** [comment]
Thanks. 
The specific use is generating a dynamic font sampler, filtered by attributes and present in a browsable overview, preferably with custom text. The current browser isn't very convenient for that but still useful, I hope that its functionality will not simpy vanish.
