### ISSUE TITLE
Font Manager Crashes on Startup (Flatpak)

### ISSUE THREAD

**Issue by bshor** [FontManager/font-manager#350]
**Describe the bug**

I am running Bazzite, an immutable Fedora 39 distro based on Kinoite (KDE). I install almost all apps via Flatpak.

When I start the program, I get an immediate crash and the following error

![image](https://github.com/FontManager/font-manager/assets/468070/e7c7c9ac-7de5-481a-b7e4-83c0f9139cce)

**To Reproduce**
1. Click on the app icon in the launcher.

**Expected behavior**
Not crash!

**Screenshots**
See above
**System Information**
 - OS: Bazzite 39
 - Desktop Environment: KDE
 - Font Manager version: Latest 
 - Font Manager installation method: Flatpak

**Additional context**

**Comment by JerryCasiano** [comment]
> Not crash!

For it to crash it would have to have actually launched in the first place.

Run it from the command line and post any output. 

This is most likely a configuration issue on your system and this issue will likely get closed as invalid....

**Comment by bshor** [comment]
Hmmm. Works now. Probably an upstream distro issue that resolved itself. Thank you.
