### ISSUE TITLE
Order of preferred fonts in substitution settings is reversed 

### ISSUE THREAD

**Issue by Alan-Kuan** [FontManager/font-manager#351]
Hi.

I set substitution for some fonts with font manager, and found that the lists of fonts in the generated config were in reversed order. Though I could just fill these fonts in reversed order beforehand, this is not that intuitive.

Would you like to fix this? Thanks.

![image](https://github.com/FontManager/font-manager/assets/24734750/1030c240-3a89-474d-b928-73ab0a4e9a0d)

![image](https://github.com/FontManager/font-manager/assets/24734750/4bdbcdea-3e40-42dc-a154-35ab20198df4)

**Comment by JerryCasiano** [comment]
Thanks for noticing and reporting this.

**Comment by Alan-Kuan** [comment]
Sure thing.
