### ISSUE TITLE
runtime org.gnome.Platform branch 44 is end-of-life

### ISSUE THREAD

**Issue by StudioCrash** [FontManager/font-manager#354]
When updating Flatpak on Arch Budgie I get the following error:

Info: runtime org.gnome.Platform branch 44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   org.gnome.FontManager

**Comment by JerryCasiano** [comment]
I don't handle the flatpak packaging and have no idea what this entails. 

You should file this at https://github.com/flathub/org.gnome.FontManager/issues

The maintainer can let me know what if any changes they need applied. 

Thanks.

**Comment by StudioCrash** [comment]
Hi.  Thanks for the info. I'll file it with the flathub link you provided.

Oh, and thank you for your work on FontManager btw!
