### ISSUE TITLE
Failure to build with newer Vala

### ISSUE THREAD

**Issue by EbonJaeger** [FontManager/font-manager#355]
**Describe the bug**
When building with Vala 0.56.17, `font-manager` fails to build with the following error:

```
../src/font-manager/ArchiveManager.vala:26.97-26.106: error: internal: invalid array_length for given dimension
   26 |     public abstract void add_to_archive (string archive, [CCode (array_null_terminated = true)] string? [] uris, bool use_progress_dialog) throws DBusError, IOError;
      |                                                                                                 ^~~~~~~~~~
../src/font-manager/ArchiveManager.vala:27.75-27.84: error: internal: invalid array_length for given dimension
   27 |     public abstract void compress ([CCode (array_null_terminated = true)] string? [] uris, string destination, bool use_progress_dialog) throws DBusError, IOError;
      |                                                                           ^~~~~~~~~~
Compilation failed: 2 error(s), 0 warning(s)
```

I'm not entirely sure if this is a Vala bug, or not; the release notes for 0.56.17 have the following entries that look relevant:

> + Update array length variable passed to null-terminated ref parameter
> + Only handle null-terminated array as such if there is no length given

**To Reproduce**
1. Build the project

**Expected behavior**
The project to build successfully.

**Screenshots**
n/a

**System Information**
 - OS: Solus 4.5
 - Desktop Environment: Budgie Desktop
 - Font Manager version: 0.8.8
   - IMPORTANT : Do not file issues for extremely outdated versions of the application.
                 Verify the issue can be duplicated with the latest release.
                 If you are running a "Long Term Support" version please open an issue at your distributions bug tracker instead
 - Font Manager installation method: Solus eopkg repository

**Additional context**
This was uncovered when trying to rebuild `font-manager` in the Solus repository in response to a user support request. An issue was filed at the Solus repository, [here](https://github.com/getsolus/packages/issues/2441).

**Comment by JerryCasiano** [comment]
Confirmed.

Not sure it's a Vala bug, but it's definitely a breaking change. 

I'll patch this later today. 

Are you allowed to patch packages? Or do you require a release?

**Comment by EbonJaeger** [comment]
While releases are always preferred, we can indeed simply add patches. Thanks!

**Comment by JerryCasiano** [comment]
The last commit allows the build to complete on Fedora 40 which uses the same Vala version. If there are any issues on Solus please let me know.

I would do a release but the next release in the 0.8 series will be the last release targeting GTK 3 so I'm trying to hold off as long as possible.

If you could apply the changes present in Git since the last release to your package that would be ideal.

Thanks!

**Comment by EbonJaeger** [comment]
Issue confirmed fixed. Thanks again!
