### ISSUE TITLE
font-manager 0.8.9 release is missing

### ISSUE THREAD

**Issue by hosiet** [FontManager/font-manager#357]
In https://github.com/FontManager/font-manager/commit/9c52ed802841eed2bd9ed4f1c7d662dd94a112dc , it is claimed that font-manager v0.8.9 is released. However, the release does not appear in either https://github.com/FontManager/font-manager/releases or https://github.com/FontManager/font-manager/tags .

Please consider making a release or at least a tag. Thanks!

**Comment by JerryCasiano** [comment]
It hasn't actually been released yet. 

Once it does it'll get a tag and appear on the releases page as usual.

So if you're interested in new releases you should track either tags or the release page itself. 

I'll keep this mind going forward and make sure I do the usual "bump version" message instead so there's no confusion...
