### ISSUE TITLE
Maximized state/panel size not saved

### ISSUE THREAD

**Issue by Moilleadoir** [FontManager/font-manager#386]
**Describe the bug**
The keys in dconf for `is-maximized` and other panel size keys are not saved on exit.

**To Reproduce**
1. Open Font Manager
2. Maximize the window and resize panels
3. Exit and relaunch
4. Program reverts to non-maximized, non-wide layout

**Expected behavior**
Should save sizing and state.

**Screenshots**
![pic](https://github.com/user-attachments/assets/c986ab8a-9a37-4c02-8327-9fa5098dad48)

**System Information**
 - OS: Manjaro
 - Desktop Environment: Cinnamon
 - Font Manager version: 0.9.0-1
 - Font Manager installation method: Official repo

**Additional context**
The startup mode is `manage`.
If I set `is-maximized` in dconf, the program starts maximized, but still doesn’t save the panel sizes.
I’ve tried resetting the the size keys (`content-size, hor-content-size, hor-sidebar-size, sidebar-size`) to defaults in dconf, but the font list is still really narrow on startup (1 letter of font name visible) and the preview pane is too wide (~65-75% though default should be 40?). After closing the program, the default values seem to be updated with actual values (e.g. `content-size: 39.985218033998521` vs. default: 40), but the actually displayed size doesn’t change.

**Comment by JerryCasiano** [comment]
Please build from master and verify this is still an issue as I can't duplicate this and there are definitely changes in master that apply to pane positions.

**Comment by JerryCasiano** [comment]
Ignore previous post I misunderstood your issue.

Looking into whether this is an issue with how we're restoring that state or not.

**Comment by JerryCasiano** [comment]
Thanks for reporting this.
