### ISSUE TITLE
Can’t scroll through font list

### ISSUE THREAD

**Issue by Moilleadoir** [FontManager/font-manager#387]
**Describe the bug**
When scrolling through font list it jumps a long way forward then back to the top.

**To Reproduce**
1. Open Manage view
2. Use mouse-wheel to scroll font list (or click a font and use page down)
3. View starts to scroll then jumps towards the end, then returns to the top of the list
4. When using mouse, the program stops reacting to input, but can be shut down
5. Preview text is scrambled/truncated

**Expected behavior**
List should scroll.

**System Information**
 - OS: Manjaro
 - Desktop Environment: Cinnamon
 - Font Manager version: 0.9.0-1
 - Font Manager installation method: Official repo

**Comment by JerryCasiano** [comment]
Unable to duplicate this, possible I'm not actually understanding the issue correctly.

But scrolling (mouse, touchpad, keyboard) appear to be working as well as it gets with GTK 4 here.

GTK 4 itself has some documented issues with regards to LIstView scrolling but that doesn't appear to be what you're describing.

https://github.com/user-attachments/assets/224a0e46-50c1-43ea-bb4f-bc1a9df5b675

**Comment by Moilleadoir** [comment]
https://github.com/user-attachments/assets/f7d042f2-fd39-456c-9253-a5cd9e77eecc

Output on crash:
```
~$ font-manager

(font-manager:3402169): GLib-GObject-CRITICAL **: 15:50:25.273: Too many GWeakRef registered
**
GLib-GObject:ERROR:../glib/gobject/gbinding.c:805:g_binding_constructed: assertion failed: (source != NULL)
Bail out! GLib-GObject:ERROR:../glib/gobject/gbinding.c:805:g_binding_constructed: assertion failed: (source != NULL)
Aborted (memory dumped)
```

I’ve tried changing to a default Cinnamon theme and also tested on a couple of other computers running Manjaro Cinnamon.  Neither had this problem.  One PC had very few fonts, the other (laptop) a couple of hundred less than this one.  Both PCs have NVidia cards, so that’s probably not the issue.  The laptop didn’t have a mouse.

The point where it freezes is not predictable, so on the surface it looks like it isn’t a particular font, but it’s coming down to the fonts being the most obvious difference between them.  Still strange that it wasn’t a problem before.

**Comment by JerryCasiano** [comment]
Thanks. That's very helpful, at least in the sense that I now know what you're seeing on your end. Definitely looks like corruption, unfortunate that it only happens on that particular computer. 

Since it's only happening with this application? it's almost certain we're doing something wrong. 

What? I have no idea. Worst still I can't even verify I fixed it if I make changes, so hopefully something obvious pops for me. I'll have a look at that portion of the code again.

Can you make sure the GTK font selection dialog doesn't also trigger similar issues please?

**Comment by JerryCasiano** [comment]
I would be curious to see what effect commenting out line # 62 in src/font-manager/FontList.vala and recompiling has for you. 

```
// binding = item.bind_property("active", item_state, "active", flags, null, null);
```

If that works then please uncomment the line by removing the added // and instead comment out lines # 43 & 44 to see if that also resolves the issue for you.

```
// if (binding != null)
   //  binding.unbind();
```

You don't need to actually install the build just to test, you can just run it right from the build directory. i.e.

1. git clone https://github.com/FontManager/font-manager.git
2. cd font-manager
3. meson setup build
4. cd build
5. ninja
6. src/font-manager/font-manager

Make the suggested edits before running ninja and run ninja again after any edits.

**Comment by Moilleadoir** [comment]
I’ve had a quick look at the font selection (Preferences | Desktop) and although it is very slow, it doesn’t freeze or crash.  Weirdly it’s not sorted alphabetically though and if I grab the scroll handle and drag down, it’s clear it’s still adding entries which seem to be loaded in chunks.  Maybe one set beginning from the selection (Noto Sans Regular), but the others seem fairly random.  Same on the laptop, though much, much slower.
I’m guessing the Cinnamon font selector is GTK3; it’s pretty much instantaneous.
![pic](https://github.com/user-attachments/assets/368415b4-8938-4c6f-b332-f74a0cc9a2b3)

**Comment by Moilleadoir** [comment]
Thought I’d just build ‘as is’ before making changes and got this error:
```
(font-manager:329990): GLib-GIO-ERROR **: 14:51:48.312: Settings schema 'com.github.FontManager.FontManager' does not contain a key named 'browse-mode'
Trace/breakpoint trap (cuimhne dumpáilte)
```
`/org/gnome/font-manager` has both `browse-mode` and `mode`, but `/com/github/FontManager/FontManager` only has `mode`.

**Comment by JerryCasiano** [comment]
Oh, right, we added the list back to Browse mode since the last release.

Since you already have a previous installation you'll need to copy the updated schema over, sorry about that. 

From the top level font-manager directory you can do 

```
sudo cp data/com.github.FontManager.FontManager.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

To install and compile only the updated schema without installing the rest of the build. It should then run fine.

We definitely need to adjust our code to prefer the schema in the build directory in case there is already an outdated one installed. I'll put that on the TODO list.

**Comment by JerryCasiano** [comment]
Thanks.

Sounds like an issue with your installation then. 
Have you updated any libraries recently that would account for the difference, especially GTK or GLib?

Also, are you saying the build from master still doesn't save pane positions for you?

**Comment by Moilleadoir** [comment]
There was a `glibc` update yesterday and on the 12th.  I’m not quite sure what to search for GTK as heaps of packages have `-gtk` in them.

The situation at the moment: if I start the installed FM the pane showing the font list will be really narrow.  If I resize it and restart, it comes back the same.  If I then run the newly-built version I can resize it and restart and the change is saved, but the next time I run the installed version, the narrow pane comes back.

If I keep dconf-editor open the size change is reflected there — `hor-content-size` changes from the initial `5.2384675527756057` to whatever I set — but when the program restarts it goes back to the previous setting.

I’ve tried resetting all the size keys in dconf to ‘default’, but the column size always comes back.

![pic](https://github.com/user-attachments/assets/d244c8e3-9b57-4092-8ec1-21bd4c02b425)

**Comment by AbeOwitz** [comment]
I'm having similar problems.  (Standard Arch, Font Manager 0.9.0)  I want to disable a bunch of fonts I don't use.  The first few disable fine, but then the list jumps to the end, then to the top and pegs the CPU and locks up.

**Comment by JerryCasiano** [comment]
@AbeOwitz 

Does building from master also resolve your issue?

**Comment by AbeOwitz** [comment]
Yes, I just compiled it and it seems to work.  README.md was easy to follow.  Thanks!

**Comment by JerryCasiano** [comment]
@AbeOwitz 

Thanks for verifying.
