### ISSUE TITLE
Preview text does not display with all fonts

### ISSUE THREAD

**Issue by Moilleadoir** [FontManager/font-manager#388]
**Describe the bug**
Some fonts show the whole display text, some only a segment, and some revert to default “The quick brown fox…”

**To Reproduce**
1. Open in Manage mode
2. Select a font
3. Some segment of the preview is displayed
4. Program likely to crash after this happens
5. Preview text is likely to be reverted to default English text in dconf settings

**Expected behavior**
Previously all fonts displayed the whole preview text, though they didn’t have all the characters.  

**Screenshots**
**FreeSerif**
![pic](https://github.com/user-attachments/assets/b3a441ab-41f9-46b9-9e93-c7ddf4936908)

Program crashed when trying to select another font and ended up with the font list so small I couldn’t resize it.  Reset in dconf.
![pic](https://github.com/user-attachments/assets/ea0c1028-6741-4054-b61a-ef530c1654ed)

[a couple of crashes later]
**Mukti Narrow**  The preview text contains Bengali, but viewing with a Bengali font (used on Wikipedia), it reverts to the default text.
![pic](https://github.com/user-attachments/assets/42894ec0-a5c5-4ebd-9c7b-a187c094c6d5)

**System Information**
 - OS: Manjaro
 - Desktop Environment: Cinnamon
 - Font Manager version: 0.9.0-1
 - Font Manager installation method: Official repo

**Additional context**
This may have something to do with failure to render my preview text, but it’s all valid Unicode and displayed fine before. This would also affect any other users of those scripts.

**Comment by Moilleadoir** [comment]
I’ve experimented a bit with previewing fonts in Font Viewer and the same fonts that seem to regularly trigger this failure in Font Manager (e.g. Mukti Narrow, Foulis Greek) are fine in Font Viewer.

**Comment by JerryCasiano** [comment]
Thanks for the additional info.

Please either attach a text file containing the actual preview string used in its entirety or use `code tags to inline it here` so we can try to duplicate this especially in regards to the crashing.

Speaking of crashing, if you can start the application from a terminal and post any output when the application crashes that would also be appreciated.

**Comment by JerryCasiano** [comment]
Closing this out as I'm unable to duplicate.
