### ISSUE TITLE
Google Fonts text preview broken

### ISSUE THREAD

**Issue by helmo2019** [FontManager/font-manager#396]
**Describe the bug**
When trying to preview fonts from Google Fonts, the displayed text does not show. It seems like it's there, as the mouse pointer changes when hovering over the preview area, and dragging actually shows the text.

**To Reproduce**
1. Click in the top left
2. Choose 'Google Fonts'
3. Select any font
4. Observe empty preview area

**Expected behavior**
The font preview is shown (preview, waterfall, or lorem ipsum).

**Screenshots**
[Video showing the text dragging glitch](https://github.com/user-attachments/assets/39763dab-e0c0-4cb0-bede-a0c3ca2980ed)

![Demonstration](https://github.com/user-attachments/assets/e6850d4d-2e78-4680-8792-5699d587a464)

**System Information**
 - OS: Arch Linux
 - DE: Xfce
 - Font Manager version: 0.9.0
 - Font Manager installation method: Distribution package, building from source (issue occurs with both methods)

**Additional context**
I suspect this to be an issue with the WebKit rendering.

**Comment by JerryCasiano** [comment]
Any errors in the output if run from command line?

**Comment by JerryCasiano** [comment]
Unable to duplicate.

Closing due to lack of response.

Feel free to reopen once you're ready to assist in resolving this issue.
