### ISSUE TITLE
SOS!!! Font Manager Destroyed a complete Linux Mint System!!

### ISSUE THREAD

**Issue by cptX** [FontManager/font-manager#55]
Two months ago, I installed font-manager in Linux Mint 17.3.
It's the first time in my Linux career that such a small program manages to crash irreversibly a complete linux system!!!!!

After pressing the button to scan the system for fonts font-manager start hanging the system. The disk started running like crazy. After 20 minutes I had to shut the system down with hard reset....
After that the system was booting in a black screen displaying only the cursor and at the same time the disk were running like crazy.
(See the issue I openned at that time but nobody helped me so far: https://forums.linuxmint.com/viewtopic.php?f=47&t=259686 )

I never managed to recover from that situation (first time in my life I couldn't recover a linux system!!!) as nobody suggested a solution and as the problem was so mystic and I had no GUI...

So I reinstalled everything in a Linux Mint 18.3 installation (we are talking about weeks of reinstalling work and still not finished...)

Today again font-manager hooked me in the same situation and this time I didn't press the scan button. I just pressed something else which I don't remember now (maybe something in the gear menu).

The system hanged immediately, the disk started running like crazy, no application was responding. Terminal, firefox and System Monitor couldn't load, so only solution was CTRL+ALT+F1.

There with iotop I noticed that csd-xsettings and cinnamon-settings.py were running like crazy!!
I was afraid to kill these processes as I had the previous bad experience, so I returned back with CTRL+ALT+F7 and did a restart. This time Cinnamon actually responded and after a couple of minutes the restart took place (probably in 18.3 cinnamon is more responsive)

After Restart I logged in again in the terrifying black screen with the cursor. You can't imagine my frustration..... but after some minutes Cinnamon managed to load and now I have again a running system.

Please tell me why was the disk running so crazy? Are there any huge files (corrupted??) created? Should I clean something?

Of course I uninstalled Font-Manager immediately although it was a useful tool, but I didn't want to risk this to happen again.

I beg the community to check this program in Linux Mint 17.3 and 18.3 and see what is wrong!

Font-Manager has the full power to destroy irreversibly a complete Linux System!!!

**Comment by cptX** [comment]
OK something is wrong in my system although I have the GUI back. Everything now loads really slow!
Also when I run the command "sudo fc-cache -f -v" it is scanning all the existing folders in my system. This is not a normal behavior as it should scan only the font folders in my system. Of course "sudo fc-cache -f -v" never ends as it scans infinite number of folders. It looks like somewhere in the system there are declared as font folders thousand of the system folders and both font-manager and sudo fc-cache -f -v are searching for them. Probably a bug in font-manager sets as font-folders all the folders of the system!!!!!!!!

Where should I look for the folder declaration for fonts?

**Comment by cptX** [comment]
Folder /var/cache/fontconfig has 11424 files!!!!
I thought there should be only 1 cache file per font. So this looks like a result of a font-manager bug.

**Comment by cptX** [comment]
OK I found the bug:
Font manager created the file ~/.fonts.conf
in this file it is referencing .config/font-manager/directories.conf
in directories.conf is referencing the home folder so it was scanning the whole home folder

**Comment by JerryCasiano** [comment]
You're using an extremely outdated version of the application.

It's been deprecated for years...

**Comment by cptX** [comment]
Then please remove it from Ubuntu Repositories. Why are you closing this?
This can destroy peoples computers and work!!!

**Comment by cptX** [comment]
I'm going to escalate this. It's now clear to me why this application is causing such a trouble. It's obvious by the lack of responsibility of it's maintainers!

**Comment by JerryCasiano** [comment]
> It's not that I'm using an outdated version. It's that Ubuntu Repositories give this version

Aside from the fact that Ubuntu carries the updated version.
What the Ubuntu repositories or any other repository does is not my concern.

> I'm going to escalate this. It's now clear to me why this application is causing such a trouble. It's obvious by the lack of responsibility of it's maintainers!

Oh no. Please don't "escalate" this.
I don't want to get fired from my hobby project that I give away freely.

You're obviously clueless or a troll.

Either way, you can go fuck yourself

**Comment by JerryCasiano** [comment]
> Why are you closing this?

You know what you're right. 

I should keep this open as a perfect example of how not to interact with open source projects.
