### ISSUE TITLE
Confused with fonts

### ISSUE THREAD

**Issue by farzadmf** [FontManager/font-manager#74]
After I wrote this issue, I noticed it became a bit long, sorry for that. I think it's still readable, but let me know if it's not :)

---

Hi,

I might or might not be a continuation of the issue I opened before (#69), but I'm facing a dilemma here again!

I was enjoying my fonts and everything, but by accident, I noticed that one of the commands I use in terminal (`minikube`) prints emojis to the terminal, but I don't see them. So I started playing with the settings in `font-manager`, and using the following setting, I can see the emojis (first one is the settings and second one is the terminal):
![image](https://user-images.githubusercontent.com/5768792/56471748-e2032280-6423-11e9-832e-cb4936abbd97.png)
![image](https://user-images.githubusercontent.com/5768792/56471751-edeee480-6423-11e9-848b-f4457991228e.png)

BUT, my problem with the terminal is that I have downloaded and set the font to `Monaco`, and the font I'm seeing doesn't look like `Monaco` at all!

If I turn off **Use Embedded Bitmaps** in **Font Manager**, the font looks better but emojis are missing:
![image](https://user-images.githubusercontent.com/5768792/56471823-0d3a4180-6425-11e9-8599-36acf3b13e73.png)

---

#### The following experimentation uses the settings I mentioned in the beginning (**Use Embedded Bitmaps** set to enabled)

I tried playing with font size, and it seems that size `9` seems to be problematic for `Monaco`, below, the first one is `8` and the second one is `10`:
![image](https://user-images.githubusercontent.com/5768792/56471872-71f59c00-6425-11e9-8270-6dcd179f8a2c.png)
![image](https://user-images.githubusercontent.com/5768792/56471877-8df93d80-6425-11e9-9a57-255e91b16e3d.png)

*Although if you look closely at the second one, you'll see that there are some artifacts in the output, e.g., `I` in `IP` seems to be green*

This size issue seems to be something that I'm noticing in Chrome too; for example, in Lastpass vault, I see the font is `Monaco 16px`, and it looks like this:
![image](https://user-images.githubusercontent.com/5768792/56471928-1841a180-6426-11e9-812c-a82b02e1b96b.png)

If I change the font size to `17px`, It looks much better:
![image](https://user-images.githubusercontent.com/5768792/56471934-2b547180-6426-11e9-97fc-c6f276940d73.png)

But the difference with Chrome is that changing the embedded bitmap setting in font manager doesn't affect it at all!

At some point, I tried to modify NVidia settings (by running `sudo nvidia-settings`) to see if I see something. I saw a setting `Antialiasing Settings` and I changed it, but now I think I got to original values:
![image](https://user-images.githubusercontent.com/5768792/56473160-1501e200-6435-11e9-9a1c-e8264b7965cc.png)

So, I was just wondering if you can tell me what's going on here because it's annoying me :( 
- What does it seem to me that some sizes are "missing"?
- Why do I see the artifacts?

**Comment by JerryCasiano** [comment]
> What does it seem to me that some sizes are "missing"?

Because they are. 
Fonts that embed bitmaps only do so for certain sizes.

> Why do I see the artifacts?

Probably because it's using embedded bitmaps instead of the outlines.

https://en.wikipedia.org/wiki/Computer_font#Bitmap_fonts
https://docs.microsoft.com/en-us/typography/opentype/otspec150/eblc

As far as rendering differences between applications that depends on a variety of factors.
Some applications may use fontconfig only to locate fonts on the system and then do their own rendering ignoring any other settings.

See https://www.freedesktop.org/software/fontconfig/fontconfig-user.html and /etc/fonts/conf.d/README for more details about fontconfig configuration.

But you probably want to disable embedded bitmaps by default and save something like 

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <test name="family"  compare="eq">
      <string>REPLACE_WITH_EMOJI_FONT_NAME</string>
    </test>
    <edit name="embeddedbitmap" mode="assign">
      <bool>true</bool>
    </edit>
  </match>
</fontconfig>
```

to ~/.config/fontconfig/conf.d/29-enable_emoji_bitmaps.conf instead.

Closing this out as it's not actually an issue related to the application.

**Comment by farzadmf** [comment]
Thank you @JerryCasiano for your answer.

I'm going to try what you suggested. I was wondering if this could have anything to do with the display drivers.

I'm asking because I have almost the same setup on my laptop and my desktop, with the only difference being that at some point, I tried to install "official" NVidia drivers on my desktop, which I regret now because I think it messed up everything!

On my laptop, everything is working perfectly; even the issue I mentioned for Chrome is fine on my laptop (as a side note, I discovered the emojis running `minikube` on my laptop).

On my laptop when I go to **Additional Drivers** in **Software and Updates**, I see this:
![image](https://user-images.githubusercontent.com/5768792/56474029-98293500-6441-11e9-9c01-94e4c989efe3.png)

So, I think it's using the "generic" driver, but on my desktop, after trying to install "official" NVidia, I see that it's using something else, and for some reason, I cannot use this driver anymore.

I know that what I'm saying has nothing to do with this application, but you're my only hope now to get an answer :)

**Comment by JerryCasiano** [comment]
> Is there any kind of tool or something that I can use to somehow embed bitmaps for other sizes?

Font editing software such as fontforge. It's a lot of work.

> And, is there anything that I can do about the things you mentioned that "it's using embedded bitmaps instead of the outlines"?

Aside from disabling embedded bitmaps globally and only enabling them for cases where you like the result, no.

Nothing to do with graphics drivers.

The result in this case simply depends on available fonts and configuration.

**Comment by farzadmf** [comment]
Thank you @JerryCasiano for your answer.

I installed `fontforge`, and I tried to open my `Monaco.ttf` with the application. When opening, it asks me whether I want to load the embedded bitmaps:
![image](https://user-images.githubusercontent.com/5768792/56476121-f74a7200-6460-11e9-9f32-c6f654a496ef.png)

So, here I see that size `9` apparently has embedded bitmaps, but this is the size that I had problem with. What's happening here?

**Comment by JerryCasiano** [comment]
> What's happening here?

Let's see the actual bitmaps in both sizes.

Do they look the same quality?

**Comment by farzadmf** [comment]
Sorry, can you explain how to do that? This is my first time using `fontforge` and opening a `ttf` with it 😛

**Comment by JerryCasiano** [comment]
Sorry, I rarely use fontforge and the few times I have it wasn't to deal with bitmap fonts.

You'll have to figure out how to examine the bitmaps at both sizes and see if there is any difference.

Keep in mind that even if there isn't an actual difference while in fontforge, gnome-terminal and other applications may not use the same rendering method.

If both the bitmaps look identical at both point sizes 9 & 10 then you'll probably need to use fontconfig's debug variables to see what's actually being used in your terminal.

**Comment by farzadmf** [comment]
Thank you @JerryCasiano . I am really grateful for all the help you provided :+1: 

I'll see if I can figure something out; I would also appreciate if you know of a resource, tutorial, etc. or anything that would help me with this stuff.

But thank you anyways.

**Comment by JerryCasiano** [comment]
Your welcome.

A couple links that come to mind

https://wiki.archlinux.org/index.php/font_configuration
https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/
