### ISSUE TITLE
Non-English characters in family name become garbled in installation path

### ISSUE THREAD

**Issue by xosdy** [FontManager/font-manager#75]
Install [test font](https://github.com/FontManager/font-manager/files/3155817/test.font.zip). I am running the latest git version(ad076e4eccd320b89e1f70afab61772d60a32245).

## Expected path
`~/.local/share/fonts/Unknown Vendor/TrueType/经典综艺体简/经典综艺体简_regular.ttf`

## Actual path
`~/.local/share/fonts/Unknown Vendor/TrueType/??????/??????_regular.ttf`

**Comment by JerryCasiano** [comment]
Yeah. This is confirmed. I came across this before.

Is this the only font that does this for you?

If you have more than one example where this is the case that would be useful to me and make it more likely that this gets attention. As it stands I've only come across one font in thousands that does this so there's very little motivation to look into it.

Sorry, I've been ignoring this for a while now... :-(

**Comment by xosdy** [comment]
I have several fonts doesn't have an English family name. Some fonts may add failed if the name has the same length.

**Comment by JerryCasiano** [comment]
If you have several fonts which cause this to happen please attach all of them here.

**Comment by xosdy** [comment]
I have uploaded the [fonts](https://anonfile.com/H9t3J7ocnc/fonts_zip).

The font called "MF QingShu (Noncommercial)" causes this issue by the style.

**Comment by JerryCasiano** [comment]
Perfect. Thank you.

Now to find out what I'm doing wrong...

**Comment by JerryCasiano** [comment]
Could you please test with the latest revision and confirm that it resolves this issue for you?

Also, you probably want to delete the cache folder (~/.cache/font-manager) and remove the files with broken filenames.

**Comment by xosdy** [comment]
Thanks, this issue fixed.
