### ISSUE TITLE
Crashes when opens - Segmentation Fault

### ISSUE THREAD

**Issue by arthur109** [FontManager/font-manager#78]
Hey! I've been using your font manager for a while now, it's the best there is. But recently for some reason whenever I open it crashes almost immediately. I ran the command in the terminal to get the error, here it is:
[1]    5747 segmentation fault (core dumped)  font-manager
I hope this helps you, if you've got any more questions or need more info please ask!

**Comment by JerryCasiano** [comment]
I do, I need to know what OS and package version version please.

Method of installation is also helpful.
