### ISSUE TITLE
[enhancement] Compare - Use preview font-size in Family list 

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#80]
As per title. Using 0.7.4 from PPA on Xubuntu 18.04 with a 2560x1440 277mm x 155mm LCD the list font samples are often rendered too small to easily make out features that I may be using to decide which fonts to compare.

I have tried changing the Display > Target DPI from the default 96 to 234 DPI with no apparent difference.

**Comment by JerryCasiano** [comment]
Browse mode allows you to adjust size. I would say use that for now.

I might get rid of "Browse" mode completely and merge it into the normal family list at some point but that's not happening anytime soon unless someone else does the work.
