### ISSUE TITLE
[enhancement] Compare - Optionally use custom preview text to render family list samples

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#81]
It would be helpful when comparing fonts to be able to optionally use the preview custom text in the family list.

In my case I am attempting to identify a font used in an image by trying to recognise common features in the family list that deserve more detailed examination in the comparison preview itself.
I have the preview's custom text set to a sentence from the image and it would be very helpful to have a checkbox to quickly cause the family list to be rendered using the custom preview text.

**Comment by JerryCasiano** [comment]
Is there a reason you can't use browse mode for this?

Not sure what advantage the normal family listing would give you in this scenario?
