### ISSUE TITLE
[enhancement] Browse/Compare - popup properties summary per font

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#84]
When traversing large lists of fonts it would be really helpful to have either a time-delayed pop-up/pop-over dialog, or a separate 'properties' pane, on hovering over a font name (the title, not the preview rendering) showing metadata such as licence, vendor and others (if available).

**Comment by JerryCasiano** [comment]
I'd be happy to review a pull request.

Feel free to reopen at that time
