### ISSUE TITLE
[enhancement] Compare - double-click font to add to comparison pane

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#85]
The workflow is quite disruptive when needing to compare lots of fonts. We have to:

1. Select (highlight) the font in the family list
2. Move the mouse cursor to top of comparison pane
3. Press the "+" button
4. Move the mouse cursor back to the family list

It would be nice to be able to double-click on a font in the list to have it added to the comparison pane.

**Comment by JerryCasiano** [comment]
Double clicking is used for activation as that is what traditionally happens when you double click something.

I don't think most users would appreciate such a change.
