### ISSUE TITLE
[enhancement] Compare - provide ways to Select All/None in family list

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#86]
When first opening the Compare mode all fonts are selected (checkboxes ticked). There is no obvious way to deselect all.

It would be nice to have buttons that would select all/select none.

**Comment by JerryCasiano** [comment]
I'm sorry I dont understand this.

> When first opening the Compare mode all fonts are selected (checkboxes ticked). There is no obvious way to deselect all.

The checkboxes in the family list represent the fonts state, whether the font is enabled or not...

Please explain.
