### ISSUE TITLE
[enhance ment] Compare - preview common character set on hover

### ISSUE THREAD

**Issue by iam-TJ** [FontManager/font-manager#89]
When fonts are in the Compare pane it would be helpful to have a hover-induced (on a time-delay) preview of the common alpha-numeric and punctuation symbols (for Latin, effectively ASCII).

The use-case is to easily check whether a particular font that is under consideration has a complete set of (correct) symbols.

This suggestion prompted by discovering a font that looks promising but turns out it has an emoji-style symbol for the question mark (U+003F).

**Comment by JerryCasiano** [comment]
This does not seem like a good idea to me.

I suggest you enter whatever characters you need to ensure are in the font into the custom preview entry.
