### ISSUE TITLE
Reset font settings

### ISSUE THREAD

**Issue by danilkhromov** [FontManager/font-manager#91]
I downloaded Font Manager 0.7.3 and changed hinting and antialiasing settings, somehow they are not really corresponding with the settings in gnome tweak tool. 
Is it possible to delete or reset this settings without breaking anything else, maybe by deleting settings file?

**Comment by JerryCasiano** [comment]
The settings exposed in 0.7.3 are strictly related to fontconfig. 

Those panes simply allow you to generate fontconfig configuration files and do not correlate to the settings in gnome tweak tool. The settings in gnome tweak tool are stored in dconf and only affect Gnome or other environments which read those keys.

0.7.5 - the current release - added a pane which exposes the same settings gnome tweak tool does.

So... just update to the current release.
