### ISSUE TITLE
Arch package issues

### ISSUE THREAD

**Issue by Dzordzu** [FontManager/font-manager#96]
I've been trying to install font-manager on my system, but unfortunately I get  `Creation method of abstract class cannot be public`. It's associated with `BaseFontList` declaration in  `src/font-manager/FontList`

As I see, the problem has been fixed on the master branch, but still it shows up in the released package

When can I expect a new version, or patch to be released?

P.S.Using upstream package doesn't work (segfault)

**Comment by JerryCasiano** [comment]
> When can I expect a new version, or patch to be released?

A new release is a couple months away.

So feel free to submit a patch or ask the maintainer to do so for now.

> P.S.Using upstream package doesn't work (segfault)

Are you saying the latest commit did not fix the segfault for you?

c81f45a636bbc621a577f92bd4374a342fb8180e should have addressed that.

Please let me know if it didn't.

**Comment by Dzordzu** [comment]
Strange... When I use Valgrind to detect exact place of the segfault the app is working fine (has got problems with some families, but launches at all). Without it it still crashes.

## Logs

### Successful (valgrind)
```
$ valgrind font-manager                                              SIGABRT(6) ↵  2557
==44607== Memcheck, a memory error detector
==44607== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==44607== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==44607== Command: font-manager
==44607==
[font-manager]-Message: 00:11:44.126: ArchiveManager.vala:59: Install file-roller to enable archive support
==44607== Conditional jump or move depends on uninitialised value(s)
==44607==    at 0x129D5F5E: pa_shm_cleanup (in /usr/lib/pulseaudio/libpulsecommon-12.99.so)
==44607==    by 0x129D789F: pa_shm_create_rw (in /usr/lib/pulseaudio/libpulsecommon-12.99.so)
==44607==    by 0x129E2B94: pa_mempool_new (in /usr/lib/pulseaudio/libpulsecommon-12.99.so)
==44607==    by 0x129924FA: pa_context_new_with_proplist (in /usr/lib/libpulse.so.0.21.1)
==44607==    by 0xEEB607C: ??? (in /usr/lib/libcanberra-0.30/libcanberra-pulse.so)
==44607==    by 0xEEB69D6: pulse_driver_open (in /usr/lib/libcanberra-0.30/libcanberra-pulse.so)
==44607==    by 0x4FC4F7B: ??? (in /usr/lib/libcanberra.so.0.2.5)
==44607==    by 0x4FBC188: ??? (in /usr/lib/libcanberra.so.0.2.5)
==44607==    by 0x4FBCEB3: ca_context_play_full (in /usr/lib/libcanberra.so.0.2.5)
==44607==    by 0x4FB52EA: ca_gtk_play_for_widget (in /usr/lib/libcanberra-gtk3.so.0.1.9)
==44607==    by 0x4FAD850: ??? (in /usr/lib/gtk-3.0/modules/libcanberra-gtk3-module.so)
==44607==    by 0x5AB035B: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
$ valgrind font-manager                                              SIGABRT(6) ↵  2557
==44607== Memcheck, a memory error detector
==44607== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==44607== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==44607== Command: font-manager
==44607==
[font-manager]-Message: 00:11:44.126: ArchiveManager.vala:59: Install file-roller to enable archive support
==44607== Conditional jump or move depends on uninitialised value(s)
==44607==    at 0x129D5F5E: pa_shm_cleanup (in /usr/lib/pulseaudio/libpulsecommon-12.99.so)
==44607==    by 0x129D789F: pa_shm_create_rw (in /usr/lib/pulseaudio/libpulsecommon-12.99.so)
==44607==    by 0x129E2B94: pa_mempool_new (in /usr/lib/pulseaudio/libpulsecommon-12.99.so)
==44607==    by 0x129924FA: pa_context_new_with_proplist (in /usr/lib/libpulse.so.0.21.1)
==44607==    by 0xEEB607C: ??? (in /usr/lib/libcanberra-0.30/libcanberra-pulse.so)
==44607==    by 0xEEB69D6: pulse_driver_open (in /usr/lib/libcanberra-0.30/libcanberra-pulse.so)
==44607==    by 0x4FC4F7B: ??? (in /usr/lib/libcanberra.so.0.2.5)
==44607==    by 0x4FBC188: ??? (in /usr/lib/libcanberra.so.0.2.5)
==44607==    by 0x4FBCEB3: ca_context_play_full (in /usr/lib/libcanberra.so.0.2.5)
==44607==    by 0x4FB52EA: ca_gtk_play_for_widget (in /usr/lib/libcanberra-gtk3.so.0.1.9)
==44607==    by 0x4FAD850: ??? (in /usr/lib/gtk-3.0/modules/libcanberra-gtk3-module.so)
==44607==    by 0x5AB035B: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==44607==
```

### Unsucessful
```
$ font-manager                                                                  ✔  2561
[font-manager]-Message: 00:19:11.308: ArchiveManager.vala:59: Install file-roller to enable archive support
double free or corruption (out)
[1]    46303 abort (core dumped)  font-manager
```

## Screenshots
### App
![image](https://user-images.githubusercontent.com/17514622/64897518-f6baae00-d683-11e9-956a-19c81462065e.png)

### Successful (valgrind)
![image](https://user-images.githubusercontent.com/17514622/64897540-105bf580-d684-11e9-8aca-f0f4c8981403.png)

### Unsuccessful (command)
![image](https://user-images.githubusercontent.com/17514622/64897564-2ff31e00-d684-11e9-9e89-de31a8bcac21.png)

**Comment by JerryCasiano** [comment]
Huh.
That is strange.
What does gdb have to say?

I'm assuming you're familiar with gdb based on you running it in valgrind, if you're not it's pretty easy you just run gdb /path/to/program which drops you into a shell, there you just type r to run the program and hit enter once it crashes typing bt and hitting enter should give you a trace.

For what it's worth, it runs fine on both Fedora and Ubuntu.

Guess I'm going to have to install Arch for testing...

**Comment by JerryCasiano** [comment]
Thanks again for reporting this and get free to reopen if the issue isn't resolved for you.

**Comment by Dzordzu** [comment]
Thanks a lot. Now there are no memleaks
