### ISSUE TITLE
Saving collections

### ISSUE THREAD

**Issue by herrlittelmann** [FontManager/font-manager#99]
Is there any possibility to _save_ my collections? From time to time I reinstall my linux system and it would be a pity when I had to reorganize my font collections.

**Comment by JerryCasiano** [comment]
For now just copy ~/.config/font-manager over to your new system.

Some kind of import/export option isn't a bad idea though, so leaving this open as a reminder.

**Comment by herrlittelmann** [comment]
Thank you for your quick and helpful response!
